### ISSUE TITLE
rmt-cli sync issues

### ISSUE THREAD

**Issue by sahara101** [SUSE/rmt#1013]
Hello, 

we cannot get the service rmt-server-sync to work. After some minute sit always sets itself to failed with this message:

Started Synchronize RMT with SCC.
SCC API request failed. Error details:
Request URL: https://scc.suse.com/connect/organizations/products?page=1
Response code: 0
Return code: operation_timedout
Response body:
RMT version 2.13
INFO: Downloading data from SCC
INFO: RMT version 2.13
INFO: Updating products
rmt-server-sync.service: Main process exited, code=exited, status=1/FAILURE
rmt-server-sync.service: Failed with result 'exit-code'.

Yet, is I run the command rmt-cli sync manually, it looks fine, no errors. 

Any ideas? Thanks!

**Comment by sahara101** [comment]
so it seams that starting the command from systemd or manually from any other user is giving the same error, timedout. 

The complete path of the command is /usr/bin/ruby.ruby2.5 /usr/share/rmt/bin/rmt-cli sync 
It is using the user _rmt

Starting the comand manually from root works every time, why is this?

**Comment by digitaltom** [comment]
If it works as root, but times out when run as another user it's most probably related to something that is in the ENV of the root user, but missing from the others. Or some sort of policy that doesn't allow other users to connect. 
Does your system use a proxy?

**Comment by sahara101** [comment]
yes, the system uses a proxy. But the weird part is that it fails also when starting it via systemctl status rmt-server-sync.service.
The service is started from the root account.

**Comment by sahara101** [comment]
Thank you, all good now. I tried to send the ENV to systemd, forgot that rmt.conf has the option

**Comment by ngetahun** [comment]
@sahara101 I'm closing this issue. Please open another issue if you run into issues.
