### ISSUE TITLE
Move documentation for rmt.conf to it's own manpage

### ISSUE THREAD

**Issue by jonsger** [SUSE/rmt#1017]
I think it would be nice if the documentation for `rmt.conf` would be in it's own man page (`man rmt.conf`).

At least the formatting in the CONFIGURATION sectioin should look more like:
```
key
  default-value
  Explanation
```

**Comment by ngetahun** [comment]
This is a duplicate of #850

**Comment by jonsger** [comment]
Ah, didn't saw that.
