### ISSUE TITLE
RMT CLI logfile info for Mirroring

### ISSUE THREAD

**Issue by ramzcode** [SUSE/rmt#1023]
Hi Team,

I just started using RMT and Planning to build Ansible Automations for RMT Server and Mirroring, Right now I am good with the Validations from the rmt-cli and trying  to find a way how the logs are being processed and saved.

Looks like I am unable to find a logfile for the RMT-CLI specially for the mirror options. I am want to know if there are file deep into that I am missing before I start using the redirection operators. I don't think that rmt-cli mirror also uses different exit codes to make final judgements.

Though I can see from other post a file with logs are listed I don't see any documents on the same.

Please share insights, thanks in advance.

**Comment by digitaltom** [comment]
rmt-cli only logs to stdout. When it's called by the systemd timer, systemd captures the logs, and they can get viewed with: 
`journalctl -u rmt-server-mirror --since yesterday -f` for example.

**Comment by ramzcode** [comment]
Great, can you please let know how can i set this cause running the same does not give me any lines. Not sure if i am missing something

**Comment by ramzcode** [comment]
Got it, the dedicated mirror service has this ability to log into the logging system and eventually it goes to messages log file, but can we even use a dedicated log file for the same ?

**Comment by digitaltom** [comment]
I'm not sure if systemd has an option to redirect the process logs to a dedicated file. It's the first request of that type, what's your use case? 
When you call `rmt-cli` directly on the console, you would be able to redirect the output to a file of your choice.

**Comment by ramzcode** [comment]
I want to maintain a log for Historical, Audit purposes and also I want the Automation to be sure if the mirror or repo sync completed without any errors. 

It looks like the rmt-cli has two exit codes with 0 & 1 so I can use that along with the redirected log file content validations. As of now I feel this is how it can work. Thank you @digitaltom
