### ISSUE TITLE
rmt-mirror reports error from cron job, but ok from command-line on opensuse15.5

### ISSUE THREAD

**Issue by huanghaiqing1** [SUSE/rmt#1033]
here we have on opensuse15.5 with rmt deployed. We can mirror all custom repos by "rmt-cli mirror" directly from command. But when we deploy it from cron job, all failed with below similar warnings. Can anyone address issue we met? Thanks.

autoyast1:~ # cat /var/log/rmt.log
I, [2023-09-04T11:01:02.583726 #14545]  INFO -- : Mirroring repository opensuse155-backports-x86_64-test to /usr/share/rmt/public/repo/opensuse/update/leap/15.5/backports/
W, [2023-09-04T11:01:03.252001 #14545]  WARN -- : Downloading http://mirrors.tuna.tsinghua.edu.cn/opensuse/update/leap/15.5/backports.license/directory.yast failed with http://mirrors.tuna.tsinghua.edu.cn/opensuse/update/leap/15.5/backports.license/directory.yast - request failed with HTTP status code 0, return code 'recv_error'. Retrying 4 more times after 2 seconds
W, [2023-09-04T11:01:05.468627 #14545]  WARN -- : Downloading http://mirrors.tuna.tsinghua.edu.cn/opensuse/update/leap/15.5/backports.license/directory.yast failed with http://mirrors.tuna.tsinghua.edu.cn/opensuse/update/leap/15.5/backports.license/directory.yast - request failed with HTTP status code 0, return code 'recv_error'. Retrying 3 more times after 2 seconds
I, [2023-09-04T11:01:07.838430 #14545]  INFO -- : ↓ directory.yast
W, [2023-09-04T11:01:07.841652 #14545]  WARN -- : The following errors occurred while mirroring:
W, [2023-09-04T11:01:07.841767 #14545]  WARN -- : Repository 'opensuse155-backports-x86_64-test' (opensuse155-backports-x86_64-test): Error while mirroring license files: bad URI(is not URI?): <TITLE>Kerberos V5 Authentication Redirection</TITLE%3E.
W, [2023-09-04T11:01:07.841870 #14545]  WARN -- : Mirroring completed with errors.

**Comment by digitaltom** [comment]
Could it be that you have a proxy configured in your ENV, which is not used when calling via cronjob? 
The "Kerberos V5 Authentication Redirection" output points to an authenticated proxy.

**Comment by ngetahun** [comment]
Closing stale issue
