### ISSUE TITLE
feature request: allow RMT clients to download packages that are not mirrored but accessible via RMT server

### ISSUE THREAD

**Issue by martin-0** [SUSE/rmt#1047]
Server that is directly connected to SuSE update server, updates.suse.com, is able to download any package that is available for that given system (e.g. any 15sp5 packages that it got registered for).

When RMT server is set proper products have to be enabled and mirrored. Some are big in size and are seldom used. Example of such packages: debug symbols, source packages or even midnight commander that is in big repository.

It would be a really nice feature if RMT client could download packages via RMT even if its not in RMTs mirrored repository.

**Comment by ngetahun** [comment]
Hi @martin-0,
clients can download packages directly from upstream without using RMT. You can change the mirroring directory to a transient directory if the aim is to have packages removed immediately. But I will close this issue as it doesn't align with the purpose of rmt.
