### ISSUE TITLE
rmt-cli mirror - "Checksum doesn't match" - http redirection issue

### ISSUE THREAD

**Issue by bsenf27** [SUSE/rmt#1048]
I have added "openSUSE-Leap-15.4-Updates" as repository, but since 02.11.2023 rmt-cli won't update repository any more.
Latest updates available from 04.11.2023 ( locally 2 days missing).<br>

BaseURL: http://download.opensuse.org/update/leap/15.4/oss/repodata.

<pre>
I, [2023-11-13T12:55:12.388523 #36322]  INFO -- : Mirroring repository openSUSE-Leap-15.4-Updates to /usr/share/rmt/public/repo/update/leap/15.4/oss/
I, [2023-11-13T12:55:12.521507 #36322]  INFO -- : ↓ repomd.xml
I, [2023-11-13T12:55:12.608302 #36322]  INFO -- : ↓ repomd.xml.asc
I, [2023-11-13T12:55:12.680102 #36322]  INFO -- : ↓ repomd.xml.key
I, [2023-11-13T12:55:12.988156 #36322]  INFO -- : ↓ e448c13f4747b004e9aceacf7ed544379783cc33f041f6734bb8e0e7e5aa98b3-deltainfo.xml.gz
I, [2023-11-13T12:55:13.016760 #36322]  INFO -- : ↓ 5afc6cb78c11733eb7ae0cd9dfefc5a37fba3d6530ec285484cf419be9bc7e84-suseinfo.xml.gz
I, [2023-11-13T12:55:13.087477 #36322]  INFO -- : ↓ e5cb3c7dfb836251e66d989d3ecf15faae058e515513dac89229e5bf439483bb-updateinfo.xml.gz
W, [2023-11-13T12:55:13.263296 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/100439fb7911ba6a01f0b753ff65c317b2c06e4174b478ec2399948472774716-filelists.xml.gz failed with Checksum doesn't match. Retrying 4 more times after 2 seconds
W, [2023-11-13T12:55:15.332414 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/6a13e463ec4660a2df04caa9d61cec45cf8d39e4b3a5a87a59760b5c57c700df-primary.xml.gz failed with Checksum doesn't match. Retrying 4 more times after 2 seconds
W, [2023-11-13T12:55:17.348701 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/7883e5d9413bf34b1f487c2205663e6fce7c126372070eaed04e0f44d5db34a2-other.xml.gz failed with Checksum doesn't match. Retrying 4 more times after 2 seconds
W, [2023-11-13T12:55:19.582233 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/100439fb7911ba6a01f0b753ff65c317b2c06e4174b478ec2399948472774716-filelists.xml.gz failed with Checksum doesn't match. Retrying 3 more times after 2 seconds
W, [2023-11-13T12:55:21.645452 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/7883e5d9413bf34b1f487c2205663e6fce7c126372070eaed04e0f44d5db34a2-other.xml.gz failed with Checksum doesn't match. Retrying 3 more times after 2 seconds
W, [2023-11-13T12:55:23.678801 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/6a13e463ec4660a2df04caa9d61cec45cf8d39e4b3a5a87a59760b5c57c700df-primary.xml.gz failed with Checksum doesn't match. Retrying 3 more times after 2 seconds
W, [2023-11-13T12:55:25.711034 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/100439fb7911ba6a01f0b753ff65c317b2c06e4174b478ec2399948472774716-filelists.xml.gz failed with Checksum doesn't match. Retrying 2 more times after 2 seconds
W, [2023-11-13T12:55:27.751758 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/7883e5d9413bf34b1f487c2205663e6fce7c126372070eaed04e0f44d5db34a2-other.xml.gz failed with Checksum doesn't match. Retrying 2 more times after 2 seconds
W, [2023-11-13T12:55:29.829649 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/6a13e463ec4660a2df04caa9d61cec45cf8d39e4b3a5a87a59760b5c57c700df-primary.xml.gz failed with Checksum doesn't match. Retrying 2 more times after 2 seconds
W, [2023-11-13T12:55:31.864581 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/100439fb7911ba6a01f0b753ff65c317b2c06e4174b478ec2399948472774716-filelists.xml.gz failed with Checksum doesn't match. Retrying 1 more times after 2 seconds
W, [2023-11-13T12:55:33.905918 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/7883e5d9413bf34b1f487c2205663e6fce7c126372070eaed04e0f44d5db34a2-other.xml.gz failed with Checksum doesn't match. Retrying 1 more times after 2 seconds
W, [2023-11-13T12:55:35.982836 #36322]  WARN -- : Downloading http://download.opensuse.org/update/leap/15.4/oss/repodata/6a13e463ec4660a2df04caa9d61cec45cf8d39e4b3a5a87a59760b5c57c700df-primary.xml.gz failed with Checksum doesn't match. Retrying 1 more times after 2 seconds
W, [2023-11-13T12:55:38.015173 #36322]  WARN -- : The following errors occurred while mirroring:
W, [2023-11-13T12:55:38.015243 #36322]  WARN -- : Repository 'openSUSE-Leap-15.4-Updates' (5588): Error while mirroring metadata: Checksum doesn't match.
W, [2023-11-13T12:55:38.015294 #36322]  WARN -- : Mirroring completed with errors.
The command exited with errors.
</pre>

Manually download repomd.xml  works:
curl -I http://download.opensuse.org/update/leap/15.4/oss/repodata/repomd.xml
<pre>
HTTP/1.1 200 OK
Date: Mon, 13 Nov 2023 11:57:36 GMT
Server: Apache
Last-Modified: Sat, 04 Nov 2023 09:02:02 GMT
ETag: "c39-6094fdfccec35"
Accept-Ranges:  none
Content-Length: 3129
Cache-Control: must-revalidate
Expires: Mon, 13 Nov 2023 11:59:56 GMT
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none'; img-src 'self' https://static.opensuse.org; style-src 'self' https://static.opensuse.org; script-src 'self' https://static.opensuse.org 'unsafe-inline'
Content-Type: text/xml
</pre>

But ...filelists.xml failed:
curl -I  http://download.opensuse.org/update/leap/15.4/oss/repodata/100439fb7911ba6a01f0b753ff65c317b2c06e4174b478ec2399948472774716-filelists.xml.gz 

<pre>

HTTP/1.1 302 Found
Date: Mon, 13 Nov 2023 11:58:21 GMT
Server: Mojolicious (Perl)
Cache-Control: public, max-age=300
Location: http://ftp.uni-bayreuth.de/linux/opensuse/update/leap/15.4/oss/repodata100439fb7911ba6a01f0b753ff65c317b2c06e4174b478ec2399948472774716-filelists.xml.gz
Vary: Accept,COUNTRY,X-COUNTRY,Fastly-SSL
Content-Type: application/x-gzip
</pre>

I think, ruby code (downloader.rb) does not catch http errorcode 302 and reload new location ..?

Don't know howto patch as described here: https://stackoverflow.com/questions/13385671/ruby-how-to-download-a-file-if-the-url-is-a-redirection ..)

Bernd.

**Comment by bsenf27** [comment]
Version installed:
rmt-server-2.14-150500.3.6.1.x86_64

Bernd.

**Comment by ngetahun** [comment]
Hi @bsenf27,
Tested mirroring leap with rmt 2.14 and seems to be working. Please re-install rmt and try again. Re-open this issue if the problem still persists.
