### ISSUE TITLE
Permission Denied - NFS Share

### ISSUE THREAD

**Issue by kevinrsalisbury** [SUSE/rmt#107]
I believe I'm using the latest build, however I receive a permission denied using rmt-cli mirror. Obviously I'm doing something wrong, but what? RPM version status (from zypper), sample rmt-cli mirror error, and permissions checks are below;

Information for package rmt-server:
-----------------------------------
Repository     : systemsmanagement:SCC:RMT (SLE_12_SP3)                  
Name           : rmt-server                                              
Version        : 0.0.3-23.1                                              
Arch           : x86_64                                                  
Vendor         : obs://build.opensuse.org/systemsmanagement              
Installed      : Yes                                                     
Status         : up-to-date                                              
Source package : rmt-server-0.0.3-23.1.src

**server:/var/lib/rmt # rmt-cli mirror**
```
WARNING: Nokogiri was built against LibXML version 2.9.1, but has dynamically loaded 2.9.4
Mirroring repository SLE-12-GA-Desktop-NVIDIA-Driver to /usr/share/rmt/public/repo
I, [2018-02-19T14:16:22.481536 #14874]  INFO -- : No product license found
I, [2018-02-19T14:16:22.491409 #14874]  INFO -- : ↓ repomd.xml
I, [2018-02-19T14:16:22.494395 #14874]  INFO -- : ↓ repomd.xml.key
I, [2018-02-19T14:16:22.497288 #14874]  INFO -- : ↓ repomd.xml.asc
I, [2018-02-19T14:16:22.504016 #14874]  INFO -- : ↓ f210b539c39142308b91f14b82200bbb5e0cc31d9ab2bb6aad2d77da3a4d9d47-filelists.xml.gz
I, [2018-02-19T14:16:22.514136 #14874]  INFO -- : ↓ 1f6d42da5f7bcf8d6d1e6b1563afa5f02dbacc1b4fe45e5be6913cfaea389327-other.xml.gz
I, [2018-02-19T14:16:22.520069 #14874]  INFO -- : ↓ b37db1bf66214660a90df2e0220ca726f6f0adefa662ef5ea9baffe9d9ab113e-primary.xml.gz
Traceback (most recent call last):
	20: from /usr/bin/rmt-cli:40:in `<main>'
	19: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	18: from /usr/share/rmt/lib/rmt/cli/base.rb:22:in `dispatch'
	17: from /usr/share/rmt/lib/rmt/cli/base.rb:33:in `handle_exceptions'
	16: from /usr/share/rmt/lib/rmt/cli/base.rb:22:in `block in dispatch'
	15: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	14: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	13: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	12: from /usr/share/rmt/lib/rmt/cli/main.rb:26:in `mirror'
	11: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'
	10: from /usr/lib64/rmt/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.4/lib/active_record/relation/delegation.rb:39:in `each'
	 9: from /usr/share/rmt/lib/rmt/cli/main.rb:26:in `block in mirror'
	 8: from /usr/share/rmt/lib/rmt/cli/base.rb:90:in `mirror!'
	 7: from /usr/share/rmt/lib/rmt/mirror.rb:37:in `mirror'
	 6: from /usr/share/rmt/lib/rmt/mirror.rb:169:in `replace_llectory'
	 5: from /usr/lib64/ruby/2.5.0/fileutils.rb:460:in `mv'
	 4: from /usr/lib64/ruby/2.5.0/fileutils.rb:1461:in `fu_each_src_dest'
	 3: from /usr/lib64/ruby/2.5.0/fileutils.rb:1479:in `fu_each_src_dest0'
	 2: from /usr/lib64/ruby/2.5.0/fileutils.rb:1463:in `block in fu_each_src_dest'
	 1: from /usr/lib64/ruby/2.5.0/fileutils.rb:471:in `block in mv'
**/usr/lib64/ruby/2.5.0/fileutils.rb:471:in `rename': Permission denied @ rb_file_s_rename - (/usr/share/rmt/public/repo/novell/sle12/repodata, /usr/share/rmt/public/repo/novell/sle12/.old_repodata) (Errno::EACCES)**
```
**server:/usr/share/rmt # ll**
```
total 60
<...>
**lrwxrwxrwx 1 _rmt nginx   19 Feb 19 14:08 public -> /var/lib/rmt/public**
<...>
```
**server:/var/lib/rmt # ll**
```
total 8
<...>
**lrwxrwxrwx 1 _rmt nginx   15 Feb  2 14:10 public -> /nfs_share/public**
<...>
server:/var/lib/rmt # 
```

**Comment by ikapelyukhin** [comment]
Hello, Kevin.

Could you please check the ownership of `/usr/share/rmt/public/repo/novell/sle12/` and `/usr/share/rmt/public/repo/novell/sle12/repodata` directories? They should be owned by `_rmt:nginx`.

RMT downloads fresh metadata into a temporary directory, then proceeds to download the RPM packages, at the end of the mirroring process it moves old metadata (`/usr/share/rmt/public/repo/novell/sle12/repodata`) into `/usr/share/rmt/public/repo/novell/sle12/.old_repodata`, and replaces it with the metadata from the temporary directory. This is to ensure the consistent state of the repo. The step where the move should happen is failing.

The ownership was different in earlier versions of RMT, perhaps the files were downloaded a while ago and still owned by root.

Thanks, Ivan.

**Comment by kevinrsalisbury** [comment]
Hi Ivan,

Looks good;
<...>
drwxr-xr-x 4 _rmt nginx 34 Feb 19 14:14 sle12
<...>
drwxr-xr-x 2 _rmt nginx 4096 Feb  2 10:24 repodata
<...>
Yes, they were owned by root. I did force a ownership change from root prior to running rmt-cli mirror. The user/group combo also exists on the NFS server itself. Admittedly I'm so used to root everywhere for NFS, it's likely here that I am doing something incorrectly, but the setup is so simple, I can't really see what it is. Or do you think that I should delete everything and re-mirror to the NFS share directly to see what happens?

**Comment by ikapelyukhin** [comment]
Hello, Kevin.

Are you able to mirror anything else successfully? Is that the only repository that is failing?

I would suggest removing just the `/usr/share/rmt/public/repo/novell/sle12/repodata` and `/usr/share/rmt/public/repo/novell/sle12/.old_repodata` directories.

If you want to try to troubleshoot the issue you could log in as `_rmt` (`su - _rmt`) and try renaming `/usr/share/rmt/public/repo/novell/sle12/repodata` into `.old_repodata` and see if it works with those permissions/ownership.

Thanks, Ivan.

**Comment by kevinrsalisbury** [comment]
We are getting closer. I can't login as _rmt on the rmt-server. I don't seem to have the _rmt password documented. Thought it was defined in rmt.conf, but that's for the database requirement of rmt-server, not rmt-cli. (So the NFS server user _rmt does not match my rmt-server server user _rmt - which may not matter here for this issue.) 

Where can I find/define the _rmt password for rmt-cli (besides the obvious linux user password)?

**Comment by ikapelyukhin** [comment]
`_rmt` is a system user (see `-r` flag in `man useradd`) that gets added during installation of `rmt-server` package. It doesn't have a password and it has `/bin/false` as its login shell.

You'd actually need to run `su -s /bin/bash - _rmt` as root or `sudo su -s /bin/bash - _rmt`.

I'm not sure what kind of set up would be required for the NFS server for this setup to work correctly.

**Comment by kevinrsalisbury** [comment]
Ivan - you'd nailed the issue;

_rmt@server:/usr/share/rmt/public/repo/novell/sle12/> mkdir test
mkdir: cannot create directory ‘test’: Permission denied

I'll research system user permissions and NFS shares and report back.

**Comment by ikapelyukhin** [comment]
Kevin, you could also configure RMT to run as root, please check `cli` section `/etc/rmt.conf`:
```
cli:
  user: root
  group: nginx
```

**Comment by ikapelyukhin** [comment]
(`_rmt` user is hard-coded into the systemd units, however -- so that might lead to some unexpected issues)

**Comment by kevinrsalisbury** [comment]
Ivan - as root (/etc/rmt.conf) rmt-cli mirror works fine against the NFS mount. We can close this if you like. I'll note: System user _rmt still fails and I haven't quite found the options to set the NFS mount to allow for system users anything but read-only access to the NFS mount. My rmt-server is SLES 12 SP3 using systemd of course...any idea what the issues might be? It's mirroring now - will check everything else rmt-server loading properly, etc. when it finishes.

**Comment by ikapelyukhin** [comment]
Hello, Kevin.

My guess would be that in the simplest case you'd need to set a mapping of UIDs in `/etc/nfs.map`.
Could you let me know which configuration options have you tried changing? What would you typically do for a user that has a password?

It would also be possible for you to just change the password of `_rmt` user.

Thanks, Ivan.

**Comment by kevinrsalisbury** [comment]
Ivan,

OK, thanks. At this point, I'm going to 'nuke and pave'. I think I've been through too many development version upgrades on this test server. Since the latest upgrade, I've had nothing but errors piled upon errors and I can't help but think it's just my environment. ;) I'll document a fresh install on a fresh SLE 12 SP3 server and report back. Let's close this please.

server:~ # rcrmt status
* rmt.service - RMT API server
   Loaded: loaded (/usr/lib/systemd/system/rmt.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Feb 20 09:44:13 server systemd[1]: Dependency failed for RMT API server.
Feb 20 09:44:13 server systemd[1]: rmt.service: Job rmt.service/start failed with result 'dependency'.
Feb 20 16:26:23 server systemd[1]: Dependency failed for RMT API server.
Feb 20 16:26:23 server systemd[1]: rmt.service: Job rmt.service/start failed with result 'dependency'.
Feb 20 16:26:25 server systemd[1]: Dependency failed for RMT API server.
Feb 20 16:26:25 server systemd[1]: rmt.service: Job rmt.service/start failed with result 'dependency'.
Feb 20 16:26:27 server systemd[1]: Dependency failed for RMT API server.
Feb 20 16:26:27 server systemd[1]: rmt.service: Job rmt.service/start failed with result 'dependency'.
server:~ # rcrmt-server-sync status
* rmt-server-sync.service - Sync RMT from scc
   Loaded: loaded (/usr/lib/systemd/system/rmt-server-sync.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Feb 20 16:26:25 server systemd[1]: Dependency failed for Sync RMT from scc.
Feb 20 16:26:25 server systemd[1]: rmt-server-sync.service: Job rmt-server-sync.service/start failed with result 'dependency'.

server:~ # rcrmt-server-mirror status
* rmt-server-mirror.service - Mirror RMT
   Loaded: loaded (/usr/lib/systemd/system/rmt-server-mirror.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Feb 20 16:26:23 server systemd[1]: Dependency failed for Mirror RMT.
Feb 20 16:26:23 server systemd[1]: rmt-server-mirror.service: Job rmt-server-mirror.service/start failed with result 'dependency'.
server:~ # rcrmt-server-migration status
If 'rcrmt-server-migration' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf rcrmt-server-migration

server:~ # rcrmt-migration status
* rmt-migration.service - RMT database setup
   Loaded: loaded (/usr/lib/systemd/system/rmt-migration.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2018-02-20 16:26:27 EST; 14h ago
 Main PID: 8817 (code=exited, status=1/FAILURE)

Feb 20 16:26:27 server rails[8817]: /usr/share/rmt/bin/rails:9:in `require'
Feb 20 16:26:27 server rails[8817]: /usr/share/rmt/bin/rails:9:in `<main>'
Feb 20 16:26:27 server rails[8817]: Tasks: TOP => db:migrate
Feb 20 16:26:27 server rails[8817]: (See full trace by running task with --trace)
Feb 20 16:26:27 server rails[8817]: == 20180102134941 AddRootAndRecommendedToProductsExtensions: migrating ========
Feb 20 16:26:27 server rails[8817]: -- add_column(:products_extensions, :recommended, :boolean)
Feb 20 16:26:27 server systemd[1]: rmt-migration.service: Main process exited, code=exited, status=1/FAILURE
Feb 20 16:26:27 server systemd[1]: Failed to start RMT database setup.
Feb 20 16:26:27 server systemd[1]: rmt-migration.service: Unit entered failed state.
Feb 20 16:26:27 server systemd[1]: rmt-migration.service: Failed with result 'exit-code'.

server:~ # rcrmt-server-sync status
* rmt-server-sync.service - Sync RMT from scc
   Loaded: loaded (/usr/lib/systemd/system/rmt-server-sync.service; enabled; vendor preset: disabled)
   Active: inactive (dead)

Feb 20 16:26:25 server systemd[1]: Dependency failed for Sync RMT from scc.
Feb 20 16:26:25 server systemd[1]: rmt-server-sync.service: Job rmt-server-sync.service/start failed with result 'dependency'.

**Comment by ikapelyukhin** [comment]
Sorry for your trouble. Looks like the DB migration is failing. RMT is under heavy development at the moment, especially in areas related to packaging, systemd integration, etc. 
Please let us know if you run into any other issues.
