### ISSUE TITLE
Starting mysql on Leap 42.3

### ISSUE THREAD

**Issue by keichwa** [SUSE/rmt#109]
In the README you say:

```
    You can create a MySQL/MariaDB user with the following command:

mysql -u root -p <<EOFF
GRANT ALL PRIVILEGES ON \`rmt\`.* TO rmt@localhost IDENTIFIED BY 'rmt';
FLUSH PRIVILEGES;
EOFF
```
> ===================================================================

But this results in this error msg on my installation:

```Enter password: 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysql/mysql.sock' (2 "No such file or directory")
```

I tried to start it first with `systemctl start mysql`, but creating the DB user still fails with:

```mysql -u root -p <<EOFF
GRANT ALL PRIVILEGES ON \`rmt\`.* TO rmt@localhost IDENTIFIED BY 'rmt';
FLUSH PRIVILEGES;
EOFF
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
````

Can you please enhance the README?

**Comment by ikapelyukhin** [comment]
Hello, Karl.

What changes do you suggest we make?

Please make sure that MariaDB is running and that you can access it as DB root user (i.e., that you can access the root console by running `mysql -u root -p`).

There also might be an issue with the version of MariaDB package you are running, I recall that older versions of the package on SLES12 require additional setup steps, such as running `mysqladmin` command (after installing the package a post-installation message appears which contains some instructions).

Thanks, Ivan.

**Comment by keichwa** [comment]
It starts for me on Leap 42.3 if I enter this sequence:

`systemctl start mysql`
`mysqladmin -u root password <xxx>`
```mysql -u root -p <<EOFF
GRANT ALL PRIVILEGES ON \`rmt\`.* TO rmt@localhost IDENTIFIED BY 'rmt';
FLUSH PRIVILEGES;
EOFF
```
and as password enter `<xxx>`.  (Instead of `<xxx>` use your password).  Thus it would probably help if you say first:

=================================================================================
Make sure that MariaDB is running and that you can access it as DB root user (i.e., that you can access the root console by running `mysql -u root -p`).  For example, use these command (instead of `<xxx>` use your password):

`systemctl start mysql`
`mysqladmin -u root password <xxx>`

=================================================================================

**Comment by ikapelyukhin** [comment]
Thanks for letting us know. I've updated the documentation.
