### ISSUE TITLE
rmt-cli mirror should use better temporary directory

### ISSUE THREAD

**Issue by olafhering** [SUSE/rmt#1137]
It seems that all files are downloaded to `/tmp` before they are moved to `/usr/share/rmt/public/repo/`.

Since the directory `/usr/share/rmt/public/repo/` points to the actual storage (the RMT admin owns that symlink), it can easily happen that `rmt-cli mirror` will run into `ENOSPC` because `/tmp` may be too small.

I suggest to use `/usr/share/rmt/public/repo/.tmp` as temporary storage, unless TMPDIR is already set.

**Comment by Adnilson** [comment]
Hi @olafhering we merged the changes for this fix and will let you know when this is deployed.
