### ISSUE TITLE
Is the systemd rmt.service set up right?

### ISSUE THREAD

**Issue by lagartoflojo** [SUSE/rmt#128]
From `journalctl -fu rmt`:

```
Apr 03 16:36:18 rmt systemd[1]: rmt.service: Supervising process 21822 which is not our child. We'll most likely not notice when it exits.
```

I looked into this a bit, and it seems that we're not using the recommended way for starting the Rails server (puma) with systemd. We use `type=forking` instead of `type=simple`.

[This is the recommended configuration](https://github.com/puma/puma/blob/master/docs/systemd.md#service-configuration) according to the Puma docs.

Is there a reason we do it differently?

See also  https://mikewilliamson.wordpress.com/2015/08/26/running-a-rails-app-with-systemd-and-liking-it/

**Comment by ikapelyukhin** [comment]
Not sure why exactly it is set to `forking`, I think the unit migrated into RMT repo from provisioning and that's how it is since then.
`type=simple` would make it a foreground process, which I guess is what we would want anyway for collecting logs with `jounralctl`.

**Comment by lagartoflojo** [comment]
> type=simple would make it a foreground process

Right, but "daemonized" by systemd.

@tmuntan1 I think you implemented it first, do you remember why we used `type=forking`?

**Comment by tmuntan1** [comment]
@lagartoflojo, I have no idea @ikapelyukhin created the file.

https://github.com/SUSE/rmt/commit/15c9051054485cb95572e8b04f66ab9813197f15#diff-f1101fb4f8ef50afe7e3c82f4269752c

**Comment by ikapelyukhin** [comment]
@lagartoflojo there seems to be no reason not to switch to `simple`. Let's do it then!

**Comment by lagartoflojo** [comment]
Okidoke! Will do.
