### ISSUE TITLE
introduce 100% coverage to be on par with connect

### ISSUE THREAD

**Issue by kalabiyau** [SUSE/rmt#14]
We decided that 100% test coverage is valuable to the team, that's why we introduced

https://github.com/SUSE/connect/blob/master/spec/spec_helper.rb#L8

Here we should consider the same

**Comment by ikapelyukhin** [comment]
SimpleCov measures coverage only in files that are used in tests, is possible to have whole files not covered with a single test with it.

**Comment by kalabiyau** [comment]
@ikapelyukhin please refer to http://www.rubydoc.info/gems/simplecov/SimpleCov%2FConfiguration%3Atrack_files

**Comment by ikapelyukhin** [comment]
@kalabiyau O-oh! Good stuff. :+1: 
Yep, I'll set it up.
