### ISSUE TITLE
Changing user and group likely to cause problems

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/rmt#144]
Currently it's possible to specify the user and group for `rmt-cli` commands to run with in the config:

https://github.com/SUSE/rmt/blob/6e2867b03797589a8722664babd0c856b95da89f/package/rmt.conf#L23-L25

However, the service that starts puma with the permissions specified in the service file:

https://github.com/SUSE/rmt/blob/6e2867b03797589a8722664babd0c856b95da89f/package/rmt.service#L10

This can lead to unexpected consequences: i.e., changing the config setting will not make `puma` to run as the same user, which can lead to issues with file permissions, etc.

Options:

1. Do not allow to change user in the config file at all
2. Make puma run as the user specified in the `rmt.conf` and remove the hardcode from the service

**Comment by tmuntaner** [comment]
@ikapelyukhin I would vote for option 1.
Allowing to change the user might make the supported scenario more confusing.

**Comment by thutterer** [comment]
@tmuntaner This can be closed now, right?

**Comment by ikapelyukhin** [comment]
Yep, should be fixed now.
