### ISSUE TITLE
Move business logic away from CLI code

### ISSUE THREAD

**Issue by thutterer** [SUSE/rmt#202]
I was experimenting with a web interface for RMT ([ :link:](https://hackweek.suse.com/17/projects/practice-react-and-material-ui-on-an-experimental-rmt-web-interface))

And then I found this logic in the CLI code classes:
https://github.com/SUSE/rmt/blob/bca4800d31e0b651d6eefa6ee47572b3fd1c5c54/lib/rmt/cli/products.rb#L64-L69

While this is not a real problem while we only have one CLI and no other means to manage RMT, I think this logic should be moved into or closer to the `Product` model code, since it is not possible to call this logic from a controller action, like I would need for a web interface.

**Comment by NeimadTL** [comment]
Hi @thutterer, I just know some basics in Ruby and Rails and I was wondering if a scope in the Product model would do the job for that ?

**Comment by thutterer** [comment]
Hi @NeimadTL, well, scoping allows you to specify commonly-used queries, so yes, we probably could use a scope instead of the `recommended_extensions` class method of the Product model, but that alone wouldn't solve that the cli/products.rb also calls `repository_service.change_mirroring_by_product!(set_enabled, products.uniq)` directly.

**Comment by NeimadTL** [comment]
Ok. I thought you were only talking about the code from L64 to L69. I'll do my best and I'll see what I can come up with.

why is it a problem that cli/products.rb calls `repository_service.change_mirroring_by_product!(set_enabled, products.uniq)` ?

**Comment by thutterer** [comment]
Not so long ago @tmuntaner and I had an in person conversation about this issue, when we touched this file, and agreed on not abstracting this further, as long as there is no real case to do so. And that is as long as we only have the CLI and no other means of controlling an RMT, like a web interface that would call Rails controller actions. 

From there, we would need also access to the same, mentioned code logic, that is "Given one product, enable it, and its recommended products too." Without duplicating the logic, of course :wink:

Then, having this code in a CLI-specific class, mixed with `puts` output would be an issue. To answer your question :nerd_face:

**Comment by thutterer** [comment]
Apologies for the late response!
Also for not checking the latest master branch before my earlier responses.

Because, if you look at https://github.com/SUSE/rmt/blob/master/lib/rmt/cli/products.rb, the logic around product en/disabling has grown in complexity quite a lot since this issue was opened.

So refactoring this in a way that it is more reusable *and more simple* got even harder.

> So even though it is not urgent to do as I understood (correct me if I'm wrong), it must be done.

Here, I wanna correct you actually:
With all we know now, it is neither urgent nor must it be done :relaxed: 

This is why:

- Making this logic any simpler, would be hard. I see a high risk of ending up with something more complex than what we already got.
- Moving the logic of enabling products out of the CLI class, where it is tightly coupled with outputting feedback to the terminal, would mean abstraction. Abstraction means further complexity and is only worth it if it helps to avoid duplication.
- But there is no other place, where we would need to duplicate this logic.
- *If* there was something like a web interface or a YaST module to control RMT, *only then* this extra complexity and effort to get there, would be worth it.
- But we have no plans to create either of these.
- So you would make something reusable and then use it only in one place. That is a mood exercise. While you might learn a lot from it, I cannot promise you that we will find the time to review code that doesn't improve the project.
- Because for the customer experience, it doesn't matter one bit if this got refactored or not. The customer would see the exact same output in the CLI. No new feature would be added. No issue would be fixed.

So what I recommend to you is to look through the other open issues of RMT and find something more beginner friendly.

One candidate could be #127.
This one is relativly straight-forward and would have real customer value.

**Comment by NeimadTL** [comment]
Thank you for the very detailed explanation.
Thanks for suggesting #127, I'll take a look at it ;)

**Comment by tmuntaner** [comment]
@thutterer Do you still want this to be an open issue?

**Comment by thutterer** [comment]
No I think we should close it for now.
