### ISSUE TITLE
rmt-cli repo list --all --csv headers request

### ISSUE THREAD

**Issue by donaldsolberg** [SUSE/rmt#232]
For the csv export, would be beneficial to export with headers to import into spreadsheet. "--headers"

**Comment by tmuntaner** [comment]
Hi @donaldsolberg, I'm looking into the feasibility of this issue.

I'm unsure about using `--headers`, as if we add any other file formats, `--headers` may become meaningless.

Maybe we could solve this with `rmt-cli repo list --all --csv-with-headers`?

**Comment by thutterer** [comment]
Why not just always have headers? Would save us from inventing a new option.

**Comment by tmuntaner** [comment]
That may break someone's workflow already using `--csv`

**Comment by thutterer** [comment]
I consider the current state of not having a header in the file already as broken. So adding headers now would fix it for me :wink:

**Comment by tmuntaner** [comment]
But we would break our own code at: https://github.com/SUSE/rmt/blob/master/support/rmt

**Comment by tmuntaner** [comment]
customers may have similar issues

**Comment by thutterer** [comment]
> But we would break our own code at: https://github.com/SUSE/rmt/blob/master/support/rmt

Our own code we can easily adapt at the same time.

> customers may have similar issues

Major version bump :relaxed: RMT 2.0 :tada:

**Comment by tmuntaner** [comment]
I'm not sure this is enough for a major version bump ^_^
