### ISSUE TITLE
Use `repomd_parser` Gem

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/rmt#233]
I have split off the code that parses repository metadata into a separate gem -- `repomd_parser` [[1](https://rubygems.org/gems/repomd_parser)] [[2](https://github.com/ikapelyukhin/repomd-parser)], mostly to make it possible to use in [repo-tools](https://github.com/ikapelyukhin/repo-tools).

I've done some refactoring in the gem and added access to some more metadata attributes. It would be cool to move RMT over to `repomd_parser` as well, so that it doesn't have its own implementation of those things.

Vote/comment on this issue if you think it's a good idea to do this :grimacing:

**Comment by wstephenson** [comment]
Is there no existing ruby gem to do this, eg from yast?

**Comment by ikapelyukhin** [comment]
@wstephenson well, I haven't found anything -- you are welcome to give another shot at searching, though.

**Comment by tmuntaner** [comment]
@ikapelyukhin did you want to make the PR for this or should someone in SCC do that?

**Comment by ikapelyukhin** [comment]
@tmuntaner Whoever gets to it first!

**Comment by tmuntaner** [comment]
@ikapelyukhin ok, I guess it will be whoever is more annoyed about the still open issue ^_^

**Comment by digitaltom** [comment]
Probably we could also make use of this in our 'duct-tape' code that parses repos for Patchfinder and Packagefinder.

**Comment by digitaltom** [comment]
@ikapelyukhin are the initializers from `repomd_parser` missing the `mirror_src` parameter?

**Comment by ikapelyukhin** [comment]
> @ikapelyukhin are the initializers from `repomd_parser` missing the `mirror_src` parameter?

I've dropped `mirror_src` in the gem (for the sake of versatility of the gem, `mirror_src` makes sense in the context of RMT but not necessarily in a context of the gem that parses XML).

Source packages have to be filtered out outside of calls to the gem.

**Comment by digitaltom** [comment]
Ok. That makes the task a bit more complicated, I was searching for a beginner task of 2 hours.

**Comment by ikapelyukhin** [comment]
> Ok. That makes the task a bit more complicated, I was searching for a beginner task of 2 hours.

Well, there's the risk, of course, but since it's mostly the same code inherited from the same codebase, I would expect this code:

```ruby
parser = RMT::Rpm::PrimaryXmlParser.new(
  File.join(@temp_metadata_dir, filename),
  @mirror_src
)
parser.parse
to_download = parsed_files_after_dedup(@repository_dir, parser.referenced_files)
```

To become this:

```ruby
parser = RepomdParser::PrimaryXmlParser.new(
  File.join(@temp_metadata_dir, filename)
)
parser.parse

files = parser.referenced_files
files = files.reject { |rpm| rpm.arch == 'src' } if @mirror_src

to_download = parsed_files_after_dedup(@repository_dir, files)
```

**Comment by felixsch** [comment]
This has been done. I'm closing this issue. Thank you @lcaparroz :)
