### ISSUE TITLE
Provide checksum of `rmt-client-setup`

### ISSUE THREAD

**Issue by tmuntaner** [SUSE/rmt#320]
Clients download the `rmt-client-setup` script over http. We should provide a checksum file that they can verify the downloaded file and avoid a man in the middle.

**Ideas**:
* Build this with `Make`
* @thutterer This checksum could be on the static RMT page.

**Comment by ikapelyukhin** [comment]
Include the code to accept certificates in SUSEConnect (there's already code for handling SSL-related exceptions there) and make `rmt-client-setup` obsolete! :grimacing:

**Comment by tmuntaner** [comment]
@ikapelyukhin you're right, but we'll probably have to support `rmt-client-setup` on older systems, as they would have no way to update `SUSEConnect`.

**Comment by ikapelyukhin** [comment]
@tmuntaner well, sure. But the sooner it's done in SUSEConnect, the sooner the need for supporting old systems will disappear :-)

**Comment by tmuntaner** [comment]
@lagartoflojo Do you know if we're considering this feature for SUSEConnect in the future?

**Comment by lagartoflojo** [comment]
> @lagartoflojo Do you know if we're considering this feature for SUSEConnect in the future?

if that's a desired feature, please create a card for it.
