### ISSUE TITLE
Database entries are not created for imported repo files

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/rmt#335]
If repo files already exist on the disk during mirroring (e.g., they were copied over from SMT), they are simply skipped during mirroring, no entries are created in `downloaded_files` table as it would normally happen if files were downloaded.

**Comment by felixsch** [comment]
@ikapelyukhin Do you think this is worth the effort? We are currently planning what to do next and this seems to be like a small issue only affecting rmt users which are coping rpms without the database?

**Comment by ikapelyukhin** [comment]
@felixsch yes, fixing inconsistent deduplication behavior is worth the effort. Code related to `downloaded_files` needs an overhaul, it generates a bunch of useless error messages when the files are missing on the disk too.

**Comment by tmuntaner** [comment]
@ikapelyukhin I think that this issue was closed with #585. If you feel otherwise, please reopen this issue.
