### ISSUE TITLE
Make number of puma workers and threads configurable by /etc/rmt.conf

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/rmt#357]
Currently number of threads is controlled by an environment variable -- changing this number probably would require modifying the systemd unit:

https://github.com/SUSE/rmt/blob/9b2dc7cc1c3a896fd57f8b5e5f4cff0021f6ca80/config/puma.rb#L7

Number of workers is not changeable without editing `puma.rb`:

https://github.com/SUSE/rmt/blob/9b2dc7cc1c3a896fd57f8b5e5f4cff0021f6ca80/config/puma.rb#L24

Those settings should be configurable from `/etc/rmt.conf`.

**Comment by felixsch** [comment]
Is this still important? If yes, we will add this feature soonish.

**Comment by ikapelyukhin** [comment]
@felixsch that'd be the way to tweak RMT performance. We do have some pretty busy regions in PubCloud, right now we are deploying a modified version of `config/puma.rb`. So yes, important enough.

**Comment by lagartoflojo** [comment]
Backlog card: https://trello.com/c/JyD3FVf4/4006-byowr-add-ability-to-tune-rmt-performance
