### ISSUE TITLE
Glitch in output when called with wrong arguments

### ISSUE THREAD

**Issue by digitaltom** [SUSE/rmt#363]
When calling: `# rmt-cli mirror help`
the output is: 

```
ERROR: "rmt-cli mirror" was called with arguments ["help"]
Usage: "rmt-cli \b mirror"
``` 

The \b looks like a bug, and also the output in general could be nicer, and use the same output as `rmt-cli help mirror` when called with wrong arguments.

**Comment by tmuntaner** [comment]
@digitaltom see if this pr helps you: https://github.com/SUSE/rmt/pull/380

**Comment by tmuntaner** [comment]
As for making the output nicer, we're limited by thor and how it handles usage issues: https://github.com/erikhuda/thor/blob/master/lib/thor/base.rb#L500

**Comment by digitaltom** [comment]
I see, then this is probably not easy to change
