### ISSUE TITLE
Download incorrectly skipped because of 'If-Modified-Since'

### ISSUE THREAD

**Issue by digitaltom** [SUSE/rmt#366]
Our QA lab's RMT server was running into a strange situation: 

It had outdated metadata content on its disk, but with a recent timestamp. 
Because of that, each mirror attempt was setting the 'If-Modified-Since' to a more recent date 
than the content on the CDN had, and it never got downloaded/updated on the RMT server. 

Do we actually gain anything by using the 'If-Modified-Since'? I would suggest to drop it because it can cause the customer RMT to stop mirroring without any error message.

**Comment by ikapelyukhin** [comment]
@digitaltom Well, you can go argue with the reporter of bsc#1066669 then :-)

Perhaps a more sensible solution would be to always download `repomd.xml` and then check if the referenced metadata files are actually present on disk and calculate checksums.

No such luxury for licenses, though -- it uses Yast metadata and there are no checksums there.

**Comment by digitaltom** [comment]
Ok. We could make such a situation less likely by not overwriting the metadata all the time, so they keep their original timestamp.

**Comment by ikapelyukhin** [comment]
@digitaltom But isn't that exactly how it works right now?

QA should just stop messing with the timestamps :grimacing:

What I think is missing is the mode to verify checksums of existing RPMs (like SMT's `--deepverify`, to redownload them if they are corrupted). This aggressive verification mode could also always purge the metadata.

**Comment by digitaltom** [comment]
> @digitaltom But isn't that exactly how it works right now?

My impression is that all metadata files have the timestamp of the last `rmt-cli mirror` run, regardless if they have changed.

**Comment by ikapelyukhin** [comment]
@digitaltom If the metadata hasn't changed, it's copied:

https://github.com/SUSE/rmt/blob/15c65c7025aa42913dcd4a67887c5696ebf9f0de/lib/rmt/downloader.rb#L122-L126

Copying doesn't preserve the timestamp. We can throw in `preserve: true` as an argument for `FileUtils.cp`.

But even though the timestamps change during copy, that shouldn't cause the issue -- the files were not changed on the CDN at this point anyway. (So CDN change time should still be greater than copy time next time something changes)

I see two possible things that would cause the issue:
1) Users messing with timestamps of the files (e.g., copying without preserving the timestamps). I guess there's not much to do about this with the current way caching works.
2) System clock could be wrong. It is possible that time on the machine is ahead of actual time and the timestamps on the CDN. For this we'd have to parse `Last-Modified-At` header during download and set file `mtime` to that value.

**Comment by digitaltom** [comment]
Yes, I think they copied the RMT partition without preserving timestamps, and without having mirrored for a while. I agree that not changing the timestamps during mirroring wouldn't solve it, but make things more obvious because one would be able to see when the file actually got mirrored. With that timestamp I was tricked into thinking that the file was downloaded from the CDN and is recent.

**Comment by ikapelyukhin** [comment]
@digitaltom I think adding `preserve: true` to ` FileUtils.cp` would be a good idea. Also I'd suggest adding analog `--deepverify` into the backlog :grimacing:
