### ISSUE TITLE
'rmt-cli mirror' downloads all metadata files always

### ISSUE THREAD

**Issue by digitaltom** [SUSE/rmt#368]
repomd.xml contains checksums and timestamp of the referenced files. 
Maybe it would be possible to skip downloading the additional metadata files by comparing the checksum/timestamp first and skipping the download if the file is already there.

**Comment by ikapelyukhin** [comment]
Err, no it doesn't. When HTTP request contains `If-Modified-Since` header, if the file hasn't been changed since the given date, the server responds with 304 status and an empty body. The downloader will use the existing files in this case.

**Comment by digitaltom** [comment]
So the '→' sign also indicates a 304 response on that file? I thought it got downloaded, because its changed timestamp.

**Comment by ikapelyukhin** [comment]
@digitaltom See https://github.com/SUSE/rmt/issues/366#issuecomment-474845975. Copying changes the timestamp, it's not re-downloaded.

**Comment by ikapelyukhin** [comment]
@digitaltom this issue is basically a duplicate of #366, let's close it.
