### ISSUE TITLE
rake test passes with failed tests

### ISSUE THREAD

**Issue by tmuntaner** [SUSE/rmt#379]
I've noticed that `bundle exec rake test` passes when a `bundle exec rspec spec` doesn't. We should fix this so that we can trust our RMT PR process.

See: https://travis-ci.org/SUSE/rmt/jobs/512906038

**Comment by tmuntaner** [comment]
@ikapelyukhin any ideas on how to fix this?

**Comment by ikapelyukhin** [comment]
@tmuntaner Set `fail_on_error` to `true`:

https://github.com/SUSE/rmt/blob/b820696c6bbc6ebeda5ce8af989baccf980d92b4/lib/tasks/test.rake#L13

https://github.com/SUSE/rmt/blob/b820696c6bbc6ebeda5ce8af989baccf980d92b4/lib/tasks/test.rake#L22

Not sure why it's set to false in the first place :thinking:

**Comment by tmuntaner** [comment]
It seems that you made this commend while I was editing my own comment. I will see how that fixes things.

**Comment by tmuntaner** [comment]
This should be solved with https://github.com/SUSE/rmt/pull/381

**Comment by ikapelyukhin** [comment]
@tmuntaner the syntax is `Fixes #123` [[1](https://help.github.com/en/articles/closing-issues-using-keywords)] and should be in PR description or commit message, it will automatically close the issue on merge.
(But mentions in commit messages don't look so nice in git history IMO, also usually it takes more than one commit to fix an issue :grimacing:)

**Comment by tmuntaner** [comment]
@ikapelyukhin Thanks, I will keep that in mind ^_^
