### ISSUE TITLE
Requesting a easier methode to add a certificate to the rmt install.

### ISSUE THREAD

**Issue by Philippe-CB** [SUSE/rmt#420]
Using the documentation from SuSE it's easy to install RMT using a selfsigned CA and certificate. But some of us like to have all our certificat from a single trusted authority. Sure, if you realise that rmt run on ngnix it's easy but i feel that yast2-rmt should give you that option instead of creating a new CA and certificate.

**Comment by ikapelyukhin** [comment]
If you place your certificates in locations where RMT expects them prior to running the Yast module, then certificate generation will be skipped. We could reflect this in the documentation.

Locations:

* `/etc/rmt/ssl/rmt-ca.crt` -- your CA bundle;
* `/etc/rmt/ssl/rmt-server.crt` -- server certificate;
* `/etc/rmt/ssl/rmt-server.key` -- server certificate private key.

**Comment by Philippe-CB** [comment]
You should also mention that the any chained certificate must be inserted in the certificate file, for any new users. Otherwise you get wonky results.
Not that it happened to me… ;)

De : Ivan Kapelyukhin [mailto:notifications@github.com]
Envoyé : 25 juin 2019 04:38
À : SUSE/rmt <rmt@noreply.github.com>
Cc : Philippe Comeau-Baril <Philippe.Comeau-Baril@midi.gouv.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [SUSE/rmt] Requesting a easier methode to add a certificate to the rmt install. (#420)


If you place your certificates in locations where RMT expects them prior to running the Yast module, then certificate generation will be skipped. We could reflect this in the documentation.

Locations:

  *   /etc/rmt/ssl/rmt-ca.crt -- your CA bundle;
  *   /etc/rmt/ssl/rmt-server.crt -- server certificate;
  *   /etc/rmt/ssl/rmt-server.key -- server certificate private key.

**Comment by tmuntaner** [comment]
@Philippe-CB I wrote a documentation note (https://github.com/SUSE/doc-sle/pull/621) for the location of RMT certs for in the `yast2 rmt` configuration section.

It doesn't specify the details of a creating a custom root certificate, but I hope that it could help nudge people in the right direction if they want to do so.

I will close this issue. Feel free to reopen it if you still have a concern that isn't addressed.
