### ISSUE TITLE
tool to remove orphaned registered client?

### ISSUE THREAD

**Issue by ghost** [SUSE/rmt#434]
Is there already a tool to remove orphaned/old clients from the DB? or do we have to write our own cleanup jobs?

**Comment by ikapelyukhin** [comment]
There's no `rmt-cli` command for client removal yet. `rmt-cli systems list` was introduced quite recently; if you'd like to contribute `rmt-cli systems remove` implementation -- you are welcome to do so :smile:

**Comment by ybaumy** [comment]
actually this is something I will really consider doing though. will put that on my backlog.

**Comment by ikapelyukhin** [comment]
@ybaumy feel free to reach out if you have any questions/issues.

**Comment by ikapelyukhin** [comment]
Let's actually keep the issue open unless it's resolved in some way (e.g., implemented/declined).

**Comment by ybaumy** [comment]
It's in my backlog but when i look at the database I just cannot decide how to delete clients. Probably the only way would be like clean up db with clients older then X days.. for example. I have not decided yet but if someone has a suggestion about how to handle this ... please just reply here.

**Comment by ikapelyukhin** [comment]
@ybaumy for the general use case the command should take the client login (or a list of logins) as input -- it would be something we would be happy to merge into master.

For your specific use case -- the logic is up to you, I'd suggest writing an auto-cleanup script that would take the output of `rmt-cli systems list --csv`, parse it and figure out which systems need to be deleted (last seen date field is available in the output), and then call `rmt-cli systems remove` with a list of system logins that need to be removed. I'm not sure if we'd want to merge this script into master, but you are welcome to publish as Gist or in a separate repo.

**Comment by ikapelyukhin** [comment]
Those are my though on the matter, anyway. Ping @lagartoflojo, please feel free to contribute. :-)

**Comment by lagartoflojo** [comment]
I agree, `rmt-cli systems remove <systemloginid>` would be a welcome addition!

**Comment by ybaumy** [comment]
just to give you a no sooner ready then ETA. since vacation is on the doorsteps it wont be before end of August.

**Comment by jdsn** [comment]
Please note that there are also other tables referencing the client and thus have also be deleted when a client is removed (unregistered).
These are"
- MachineData
- ClientSubscriptions
- JobQueue
- JobResults
- Patchstatus

I can create a PR to remove the dependencies within the function _deleteRegistrationLocal if you agree that this is the correct place to integrate it.
Thanks.

**Comment by lagartoflojo** [comment]
@jdsn I think those tables are in SMT, but not in RMT?

**Comment by ikapelyukhin** [comment]
@jdsn yep, wrong project. :-) SMT already has `smt-delete-registration`.

**Comment by jdsn** [comment]
sorry, came here via a link and did not notice the wrong repo :/

**Comment by ikapelyukhin** [comment]
@jdsn you are welcome to implement it for RMT, it's a highly demanded feature :grimacing:
