### ISSUE TITLE
How much storage space for RMT server?

### ISSUE THREAD

**Issue by cjschroder** [SUSE/rmt#449]
Hello SUSE RMT colleagues, what is a good recommendation for calculating the amount of storage space required on a RMT server? I need to add this guidance to the Repository Mirroring Tool Guide (https://www.suse.com/documentation/sles-15/book_rmt/data/book_rmt.html). There are almost 40,000 packages in SLE 15 SP1 x86_64 alone. Some shops will use just a small percentage of available packages, some will use everything on multiple architectures and multiple SLE releases. thanks!

**Comment by ikapelyukhin** [comment]
Hello, Carla.

Sadly, there's no simple answer for that question. Factors that contribute to how much space will be used:

* Which products are being mirrored;
* Which repos are being mirrored: some repos are optional, like DebugInfo and Source repos;
* Outdated packages are accumulated over time: when new versions come out, old version are kept in disk but aren't referenced by repo metadata anymore (so effectively invisible to the clients); RMT doesn't have a way of cleaning out those old packages and reclaiming disk space;
* Repo size might change overtime due to packages being added or removed.

I have a `repo_stats` [[1]] script which can be used to determine the size of each individual repo before downloading it -- but that perhaps it is too precise.

On Public Cloud RMTs we mirror SLES and SLES_SAP 12 SP0-SP5, SLES and SLES_SAP 15 SP0-SP1 with some of the more common modules + PackageHub -- disk spaced usaged by all those repos right now is at 430 GB, all those repos were mirrored very recently, so there are very few outdated packages yet.

HTH, Ivan.

[1]: https://github.com/ikapelyukhin/repo-tools#repo_stats

**Comment by cjschroder** [comment]
Thank you @ikapelyukhin, that helps. I was thinking of recommending twice the total repo size per distro per architecture as a guide. repo_stats looks perfect for calculating some general recommendations. Does that make sense?

**Comment by ikapelyukhin** [comment]
@cjschroder yes, I suppose providing some examples as a guide would be the best option. Let me know if you need help with getting the size stats (tens of repos with auth tokens would need to be analyzed).

**Comment by cjschroder** [comment]
Thanks @ikapelyukhin. I tried `repo_stats` and it works fine on opensuse repos, which do not need authentication. I tried `https://repo.url/?login=foo&password=bla` with my SCC credentials for the SLE repos, but that returns 403 "Forbidden". Is that not the right way?

For now, all I need is to provide some sizing examples for the larger SLE 12 & & 15 repositories. I wonder if anyone else is thinking about how to provide this information for customers. I'll search Jira/Confluence, and if not it might be worth opening a new issue.

Thanks for your help, repo-tools is fun :)

**Comment by ikapelyukhin** [comment]
> Thanks @ikapelyukhin. I tried `repo_stats` and it works fine on opensuse repos, which do not need authentication. I tried `https://repo.url/?login=foo&password=bla` with my SCC credentials for the SLE repos, but that returns 403 "Forbidden". Is that not the right way?

That's not how authentication for the repos work. Repos are hosted on the CDN and require an authentication token. Auth tokens contain subscription expiration date, they are encrypted with the CDN key and are generated for each subscription by SCC. RMT gets them from SCC during `rmt-cli sync` and stores them in the DB (`repositories.auth_token`).

> For now, all I need is to provide some sizing examples for the larger SLE 12 & & 15 repositories. I wonder if anyone else is thinking about how to provide this information for customers. I'll search Jira/Confluence, and if not it might be worth opening a new issue.

Here's some crunched data:

#### SLES 12 SP5 and extensions

| Product | Only mandatory*<br>(size in GB) | All repos**<br>(size in GB) |
| --- | --- | --- |
|SLES/12.5/x86_64|3.63|17.03|
|sle-module-legacy/12/x86_64|1.16|1.43|
|sle-module-web-scripting/12/x86_64|2.14|3.63|
|sle-module-cap-tools/12/x86_64|0.00|0.03|
|sle-live-patching/12.5/x86_64|0.00|0.00|
|sle-module-hpc/12/x86_64|0.52|0.77|
|sle-ha/12.5/x86_64|0.06|0.98|
|sle-sdk/12.5/x86_64|1.52|10.38|
|sle-module-adv-systems-management/12/x86_64|0.98|1.00|
|sle-module-containers/12/x86_64|1.75|1.87|
|PackageHub/12.5/x86_64|13.82|28.04|
|sle-module-toolchain/12/x86_64|2.34|3.80|
|sle-module-public-cloud/12/x86_64|2.32|11.63|
|**Total**|**30.26**|**80.59**|

#### SLES 15 SP1 and extensions

| Product | Only mandatory*<br>(size in GB) | All repos**<br>(size in GB) |
| --- | --- | --- |
|SLES/15.1/x86_64|0.00|0.00|
|sle-module-basesystem/15.1/x86_64|4.28|16.05|
|sle-module-desktop-applications/15.1/x86_64|3.15|9.77|
|sle-module-development-tools/15.1/x86_64|2.23|5.81|
|PackageHub/15.1/x86_64|32.56|36.44|
|sle-module-containers/15.1/x86_64|0.20|0.27|
|sle-module-server-applications/15.1/x86_64|0.89|2.39|
|sle-module-web-scripting/15.1/x86_64|0.09|0.22|
|sle-module-legacy/15.1/x86_64|0.84|4.76|
|sle-module-public-cloud/15.1/x86_64|0.42|0.98|
|sle-ha/15.1/x86_64|0.20|3.41|
|sle-module-live-patching/15.1/x86_64|0.07|3.03|
|sle-module-python2/15.1/x86_64|0.11|0.37|
|sle-module-cap-tools/15.1/x86_64|0.02|0.04|
|sle-module-transactional-server/15.1/x86_64|0.00|0.00|
|**Total**|**45.07**|**83.54**|

\* Repos that are enabled by zypper by default on client machines
\*\* All repos, including ones that are disabled by default (DebugInfo, Source, etc.)

**Comment by ikapelyukhin** [comment]
(SLES 12 SP4 and 15 SP1 are actually poor examples -- the update repos are empty, I've updated with older SP data)

**Comment by cjschroder** [comment]
Many thanks, @ikapelyukhin, this is perfect. Very much appreciate your help. I will post the link to my PR here when it is ready, and then close this issue.

**Comment by cjschroder** [comment]
If you have to review that would be fab. I elected to keep it simple and general. It would be cool if `repo_stats` became a supported tool in SLES.
https://github.com/SUSE/doc-sle/pull/462

**Comment by ikapelyukhin** [comment]
>  It would be cool if `repo_stats` became a supported tool in SLES.

That requires PMs to do PM stuff. You are welcome to create a Jira entry for including the existing package into SLES; or request this functionality to be built into RMT.
