### ISSUE TITLE
Hide non-mirrored repositories in the zypper service

### ISSUE THREAD

**Issue by digitaltom** [SUSE/rmt#476]
Currently the zypper services that RMT returns contain all repositories of a product, no matter if they are actually mirrored or not. 

A user that enables one of the not-mirrored repos will run into an an error. 

The proposed feature is to hide non-mirrored repos in the zypper service for the client systems.

**Comment by ikapelyukhin** [comment]
Currently zypper services are identical to what SCC serves. Hiding non-mirrored repos would result in different service definitions on different RMT instances. It would also conceal the fact Debug and Src repos even exist and in theory could be enabled from the end user.

My vote is for leaving it as is for consistency with SCC.

**Comment by felixsch** [comment]
@digitaltom Seeing the answer from Ivan, do you still want this feature?

**Comment by digitaltom** [comment]
I agree, it could also create confusion to have the service definitions not static. We also don't have anyone asking for that currently, so I'm closing this issue.
