### ISSUE TITLE
SLES 12 SP3 rmt-cli scc sync error

### ISSUE THREAD

**Issue by kevinrsalisbury** [SUSE/rmt#49]
Nice project! I decided to test rmt on SLES 12 SP3. After configuring rmt.conf, starting rmt with no errors, and verifying the web server is accessible on port 4224, rmt-cli fails. I have double checked all settings in my rmt.conf. Am I missing a ruby dependency or something silly? Here's the error;

`kevin:/etc # rmt-cli scc sync
/usr/share/rmt/lib/rmt/scc.rb:13:in `sync': undefined method `username' for "username:xxxxxx password:xxxxxxxx":String (NoMethodError)
	from /usr/share/rmt/lib/rmt/cli/scc.rb:10:in `sync'
	from /usr/lib64/rmt/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/lib64/rmt/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib64/rmt/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/share/rmt/lib/rmt/cli/base.rb:24:in `block in dispatch'
	from /usr/share/rmt/lib/rmt/cli/base.rb:35:in `handle_exceptions'
	from /usr/share/rmt/lib/rmt/cli/base.rb:24:in `dispatch'
	from /usr/lib64/rmt/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
	from /usr/lib64/rmt/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:238:in `block in subcommand'
	from /usr/lib64/rmt/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/lib64/rmt/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/lib64/rmt/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/share/rmt/lib/rmt/cli/base.rb:24:in `block in dispatch'
	from /usr/share/rmt/lib/rmt/cli/base.rb:35:in `handle_exceptions'
	from /usr/share/rmt/lib/rmt/cli/base.rb:24:in `dispatch'
	from /usr/lib64/rmt/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /usr/bin/rmt-cli:38:in `<main>'
`

**Comment by ikapelyukhin** [comment]
Hello, Kevin.

Thanks for taking the time to report the issue.

The config file is in YAML format, seems like there's an issue with the formatting. Could you please post your config file? (Please edit out your credentials)

The format for the `scc` section should be as follows:

```
scc:
  username: xxxxx
  password: xxxxx
```

Spaces must be used for indentation. This denotes a hash in YAML, which is what RMT expects.
I was able to replicate your issue with the following contents in the `scc` section:
```
scc: "username: xxxxx password: xxxxx"
```
This is a string rather than a hash, which would raise an exception.

Actually, we might consider choosing a different format for the config file, as YAML is pretty sensitive to formatting.

Thanks, Ivan.

**Comment by kevinrsalisbury** [comment]
Ah ha! I bet I forgot the spaces. I'm used to YAML configs, I know better. Eventually if there's a simple YAST module for this, most SLE admins will likely use that anyway. I will confirm this is the issue and report back. -Kevin

**Comment by kevinrsalisbury** [comment]
Ivan,

That was the issue indeed. Thank you again for your efforts on this - we've grown a bit tired of some SMT issues with SLE of late, and having opensuse support is fantastic for those edge cases where we use it. We will continue to watch this project with interest, as well as test and report back any other issues.

`server:/ # rmt-cli scc sync`
`I, [2017-11-06T11:20:47.322331 #23801]  INFO -- : Cleaning up the database`
`I, [2017-11-06T11:20:47.367464 #23801]  INFO -- : Downloading data from SCC`
`I, [2017-11-06T11:21:24.902792 #23801]  INFO -- : Updating products`
`I, [2017-11-06T11:22:56.273179 #23801]  INFO -- : Updating repositories`
`I, [2017-11-06T11:23:12.965261 #23801]  INFO -- : Updating subscriptions`
`I, [2017-11-06T11:23:13.890528 #23801]  INFO -- : Done!'`
