### ISSUE TITLE
No option to set "no proxy" hosts in settings

### ISSUE THREAD

**Issue by doccaz** [SUSE/rmt#491]
There is no way to set the equivalent of "http_no_proxy" for RMT. I'm running into this issue since some of the mirrors for my customer must NOT go through the proxy (local domains).

There is no provision for this in the gem used by RMT (typhoeus). There is an open issue for this exact problem: https://github.com/typhoeus/typhoeus/issues/528
... but doesn't have any activity since 2016.

**Comment by doccaz** [comment]
I forked the typheous repo and was working on adding the relevant libcurl option, when I spotted this (http_client:verbose is true in rmt.conf):

Connection #0 to host cache.bb.com.br left intact
**Uses proxy env variable no_proxy** == 'localhost,127.0.0.1,.bb,.bancobrasil.com.br,.bb.com.br'
  Trying 172.20.50.4...
TCP_NODELAY set
Connected to cache.bb.com.br (172.20.50.4) port 80 (#0)
...

So, it might be easier to just document in RMT that you can set the "no_proxy" environment variable. It's libcurl beneath all these layers, after all.

**Comment by doccaz** [comment]
I made a pull request to the typhoeus repository implementing the "noproxy" option: https://github.com/typhoeus/typhoeus/pull/642

**Comment by felixsch** [comment]
@doccaz Very nice. Could you add the documentation to https://github.com/SUSE/doc-sle. Would be really appreciated. If you need help let me know. Thank you for your efforts in RMT!

**Comment by tmuntaner** [comment]
@doccaz can we close this issue?

**Comment by doccaz** [comment]
Sure! Thank you.
