### ISSUE TITLE
Make it possible to set low_speed_limit and low_speed_time

### ISSUE THREAD

**Issue by doccaz** [SUSE/rmt#493]
In some situations, there are network content checking appliances/proxies that will hold the connection open until the entire file is fetched, and *then* the client (in this case, RMT) receives the entirety of the data stream. Since the connection is mostly receiving just a few bytes/sec until the proxy/appliance is done, RMT thinks the connection is stuck, drops it and marks the file as not downloaded. This also makes downloading any large file impossible.

Analyzing the code, I noticed that RMT is using fixed values in http_request.rb. I'm proposing a change to read these two options from rmt.conf. If they're not present, just assume the current hard-coded values.

**Comment by felixsch** [comment]
This is addressed here: https://github.com/SUSE/rmt/pull/494

The pull request has been merge, thats why I'm closing this.
