### ISSUE TITLE
Allow for multiple targets

### ISSUE THREAD

**Issue by kevinrsalisbury** [SUSE/rmt#50]
Feedback for others who may try this: For a 0.1 Release, the quality of rmt is impressive. On several test and production SLE12 systems that were having issues with SMT and/or broken SUSEConnect issues - RMT just works. Server setup is easy (had one self inflicted YAML issue), client connections are very reliable (I can't break anything yet - believe me I've tried). I have performed some simple zypper patch on SLE 12 SP3 systems that worked fine as well as some SLE 12 SP2 -> SP3 migrations on several systems with absolutely no issues. I simply followed the instructions in the GitHub readme and added a cron job for root on the rmt server to sync and mirror against the SCC daily.  Will continue to test and provide feedback, but I really like the direction this is headed.

*************
Not urgent or imperative, but I have a potential enhancement request. At the moment, if multiple targets are presented to rmt-cli, the client fails with an error;

server:/ # rmt-cli repos enable SLES/12.2/x86_64 SLES/12.3/x86_64 sle-sdk/12.2/x86_64 sle-sdk/12.3/x86_64 PackageHub/12.2/x86_64 PackageHub/12.3/x86_64 sle-module-legacy/12/x86_64 sle-module-adv-systems-management/12/x86_64 sle-module-web-scripting/12/x86_64
ERROR: "rmt-cli repos enable" was called with arguments ["SLES/12.2/x86_64", "SLES/12.3/x86_64", "sle-sdk/12.2/x86_64", "sle-sdk/12.3/x86_64", "PackageHub/12.2/x86_64", "PackageHub/12.3/x86_64", "sle-module-legacy/12/x86_64", "sle-module-adv-systems-management/12/x86_64", "sle-module-web-scripting/12/x86_64"]
Usage: "rmt-cli repos enable TARGET"

Allowing multiple targets could make autoyast / automated / scripted setups slightly easier for admins in the future. When I present one target, it works just fine.

**Comment by kalabiyau** [comment]
Hi, @kevinrsalisbury 

Thanks a lot for such thorough review, it is very heartwarming. https://scc.suse.com/team is definitely happy to have you as such an early adopter.

As for the enhancement, I think it totally makes sense. We certainly will evaluate it. 
It very much possible that it will be aligned with SLES15 SP1 though, so that you know :)
If I understood your correctly you mainly this enhancement as a part of automated scenarios. Is that deployment of rmt in automatic manner with autoyast? If so, could you share some little insights about that case?

**Comment by kevinrsalisbury** [comment]
Hi, @kalabiyau 

I'm sure you probably weren't expecting a customer to try it so soon. But we've been fighting with SMT for so long on certain systems and we've also wanted to do something proper for openSUSE Leap as well, so again, we are extremely pleased with the direction of RMT and were very happy to see it in public view. We understand it's alpha code and subject to being dropped/rewritten. No problem - we'll adjust as necessary. As for the enhancement request, I understand your questions - now that we know a better replacement is coming (RMT) we have just been evaluating all our SMT use cases and trying to see how RMT fits in all of them. We'll try to document something more complete later to explain the potential, and honestly as RMT develops further along with SLE 15 - we may change the way we work from SMT. I'll close this request for now. Feel free to reach out direct if you need something tested or reviewed, otherwise we'll just continue to patch RMT on the latest SLE and test new features as they arrive.

**Comment by ikapelyukhin** [comment]
Hello, Kevin.

Could you please tell us more about the issues that you are experiencing with SMT? I think this knowledge help us avoiding those issues in RMT.

Thanks, Ivan.

**Comment by kevinrsalisbury** [comment]
Ivan,

Sorry for the late response, I missed this reply somehow. In looking at our internal data, SMT server/clients have completely broken on us at least 14 times over the past 5 years, normally due to patches for other SLE issues not directly tied to SMT. (We routinely wondered if SMT was ever part of QA checks after SLE patches). Client/Server Private and Public Certificates in particular have been painful. We have probably run into at least half of the SMT issues covered in [TID 7005002](https://www.suse.com/support/kb/doc/?id=7005002).  Our only real advice is to keep the solution as simple as practical and perhaps see if there are [openQA](https://openqa.opensuse.org/) or equivalent scripts that can be used to look for obvious issues after building service packs for openSUSE/SLE at least...

**Comment by ikapelyukhin** [comment]
Let's keep the issue open until we properly address it.

**Comment by tmuntaner** [comment]
@kevinrsalisbury Hi Kevin,

Enabling multiple products/repositories was implemented in https://github.com/SUSE/rmt/pull/284 and https://github.com/SUSE/rmt/pull/239. These changes should make it into the next release and I hope they'll help you.

Thanks,
Thomas Muntaner

**Comment by tmuntaner** [comment]
I'm closing this issue as the new features is in master. If feel the new feature doesn't solve your issue, please feel free to reopen.
