### ISSUE TITLE
Duplicate systems in RMT

### ISSUE THREAD

**Issue by Kyzersose** [SUSE/rmt#500]
I have duplicate entries when running "rmt-cli systems list". It would be helpful if:

- When a client is being registered with an RMT server, a check is made for duplicate hostames.

- rmt-cli systems included a remove command to help cleanup orphaned entries.

**Comment by ikapelyukhin** [comment]
Hostname is not a unique identifier, especially when dealing with virtualized clients where instances can be cloned.

Clean up should be done manually, either via `SUSEConnect -d` or from the side. Server side client removal is not yet implemented (previously reported via #434).

**Comment by tmuntaner** [comment]
Hi @Kyzersose,

The functionality to remove systems was just merged in #434. This should enable you to write a simple script to find systems with duplicate hostnames and use `rmt-cli systems remove SCC_****` to remove them.

As making hostnames a unique identifier is not currently possible (see the statement from @ikapelyukhin above), I hope that the increased tooling will assist you in solving future issues.

I will close this issue, but if you feel that you still have a concern that hasn't been addressed, please feel free to reopen this and let us know.
