### ISSUE TITLE
Missing bash-completion for systems commands

### ISSUE THREAD

**Issue by thutterer** [SUSE/rmt#513]
I just noticed that is was forgotten in #423 to add Bash completion for this new command namespace.

**Comment by ikapelyukhin** [comment]
*\*cough-cough\** Dynamic bash completion?

Doesn't necessarily have to be a script executed on each tab press (as it was pretty slow as we've discovered with @simson-suse) -- could be also a rake task generate the file during packaging.

Quick search show there are existing solutions for Thor [[1]] [[2]].

[1]: https://gist.github.com/lukasz-kaniowski/1348078
[2]: https://gist.github.com/Jell/c06a7b254fdb3aaeb6ce
