### ISSUE TITLE
CLI commands "repos/products enable/disable" do too much but do not catch wrong user input

### ISSUE THREAD

**Issue by thutterer** [SUSE/rmt#55]
We still don't catch RecordNotFound exceptions when a user calls `rmt-cli repos enable 123` and that ID is not in the database. Same for products. The fix is simple: Just look ahead in the database with `find_by(id: 123)`. But when I started adding this check, I found the method `change_repository_mirroring` already too complicated and hesitated to add another if-else. 

What makes it (relatively) complicated is that we, for some reason, support `rmt-cli repos enable some/product/identifier` which I find very unnecessary. In case a user wants to enable a whole product, there is `rmt-cli products enable` ... why put this extra functionality in the repos, too?

So I suggest we drop that and make it clear that:
- `repos enable` only works with a repo id.
- `products enable` takes either a product id or a product identifier string.

Then the cognitive complexity of both method would be better.

**Comment by ikapelyukhin** [comment]
IIRC, `repos enable 123` and `product enable 123` do different things: the former enables a repo with ID 123, the latter enables a product with ID 123. Both also accept the `product/version/arch` product string.

How to do it better is open for discussion, of course. Some user testing/other 3rd-party input would be nice. Let's ping @kalabiyau for starters :grimacing:

**Comment by kalabiyau** [comment]
@ikapelyukhin I am planning a card where we will work with internal customers to see their feedback on usability. As well, there are plans to reach out to real customers and to see what do they think. For now, I believe we could live with simplest solution and improve it as we learn from users.

**Comment by kevinrsalisbury** [comment]
@kalabiyau as a real customer using rmt, we're OK so long as it's clearly documented. If maintaining better code means rmt-cli repos/product enable repo/product **id** is the best way, then that's fine by us. Initial setup of rmt-server is so simple, picking the repo/product number from the list seems trivial to us, especially if the --help and man pages explain this.

**Comment by tmuntaner** [comment]
@thutterer I think that we will keep the product id and string for the foreseeable future, as `rmt-cli products enable sles/15` will enable all architectures and a product id does not.

With the updates to `rmt-cli products enable`, do you still see the need to do something or can we close this?

**Comment by tmuntaner** [comment]
@thutterer can I close this issue?
