### ISSUE TITLE
Installer updates repos are added to registered systems

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/rmt#559]
I've noticed that clients registered to RMT and to SCC have a different number of repos after registration -- RMT-registered clients have an extra repo, `SLE15-SP1-Installer-Updates`.

Seems like zypper service XML endpoint on SCC side filters out installer update repos and RMT doesn't.

It doesn't make sense to add installer repos to the registered machines, those are supposed to be used during installation only.

**Comment by digitaltom** [comment]
SCC has this in the default scope: `scope :excluding_installer_updates, -> { where(installer_updates: false) }`
