### ISSUE TITLE
"repos --all" should tell about "sync" when DB is still empty

### ISSUE THREAD

**Issue by thutterer** [SUSE/rmt#58]
On an empy database (before the first `sync`)
```
rmt-cli repos --all
```
currently outputs
```
No repositories enabled.
```

But it should behave the same way than `products --all` which in this case already outputs
```
Run "rmt-cli sync" to synchronize with your SUSE Customer Center data first.
```

**Comment by ikapelyukhin** [comment]
@thutterer A good issue for the trainees to work on? :grimacing:

**Comment by fschueller** [comment]
See https://github.com/SUSE/rmt/pull/63.
