### ISSUE TITLE
RMT issue with cached repomd.xml

### ISSUE THREAD

**Issue by tmuntaner** [SUSE/rmt#628]
With the new error summary in RMT, we noticed that our RMT had some issues in mirroring specific repositories:

```
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: The following errors occurred while mirroring:
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLES12-Updates' (777): Error while mirroring metadata: GPG key import failed.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SUSE-CAASP-ALL-Pool' (1396): Error while mirroring license: license.de.txt - HTTP request failed with code 404.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLES12-SP4-Pool' (1676): Error while mirroring metadata: repodata/c51296a07949d055b5cb0514435bde14799a6f175e28786d38109a9951b5ade5-license.tar.gz - HTTP request failed with code 404.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-SDK12-SP4-Pool' (1684): Error while mirroring metadata: repodata/b08ac7def1dacefa1b1cad35554c9d0e91c4c955a167d04ea9f63c0f556ef93e-license.tar.gz - HTTP request failed with code 40>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Product-SLES15-SP1-Pool' (3235): Error while mirroring metadata: repodata/35b85bdc30476fd5e2adff6337d546ed341622bfc77288f27d9258f8fb8550d3-primary.xml.gz - HTTP request failed wit>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Basesystem15-SP1-Pool' (3239): Error while mirroring metadata: repodata/35b85bdc30476fd5e2adff6337d546ed341622bfc77288f27d9258f8fb8550d3-primary.xml.gz - HTTP request faile>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Desktop-Applications15-SP1-Pool' (3244): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP reque>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-DevTools15-SP1-Pool' (3249): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request failed wi>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-CAP-Tools15-SP1-Pool' (3254): Error while mirroring metadata: GPG signature verification failed.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Containers15-SP1-Pool' (3259): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request failed >
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Server-Applications15-SP1-Pool' (3264): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP reques>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Web-Scripting15-SP1-Pool' (3274): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request fail>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Legacy15-SP1-Pool' (3279): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request failed with>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Public-Cloud15-SP1-Pool' (3284): Error while mirroring metadata: repodata/fe5ca3fbbae61f1406c2135f2c995688d6e6a5e3264e11e85fc4d9f5253cbede-other.xml.gz - HTTP request faile>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SUSE-PackageHub-12-SP4-Pool' (3658): Error while mirroring metadata: GPG signature verification failed.
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Transactional-Server15-SP1-Pool' (3821): Error while mirroring metadata: repodata/48ff07ca9da787d67fdb63c2205515253ca39067b489a6f9ec634c382c346464-primary.xml.gz - HTTP req>
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Repository 'SLE-Module-Python2-15-SP1-Pool' (5122): Error while mirroring metadata: repodata/2f9f073e5b35fef5409f1e2bdb6fffcc411e7c5655a6aaa23e7e224d479ed285-primary.xml.gz - HTTP request failed >
Sep 15 03:57:14 rmt rmt-cli[18826]: WARN: Mirroring completed with errors.
Sep 15 03:57:14 rmt systemd[1]: rmt-server-mirror.service: Main process exited, code=exited, status=1/FAILURE
Sep 15 03:57:14 rmt systemd[1]: rmt-server-mirror.service: Unit entered failed state.
Sep 15 03:57:14 rmt systemd[1]: rmt-server-mirror.service: Failed with result 'exit-code'.
```

Under a closer examination, the `repomd.xml` files for these repositories had older content, but the timestamps of the files were newer than their `last-modified` response header. RMT uses this header to save time/bandwidth in the mirroring process. In this case, the timestamp is wrong and actively prevents RMT from fixing its data. I wasn't able to see how this exactly happened, it could have been many things, but we could improve on the process and make RMT more resilient to this type of failure.

One possible option that I saw to fix this could be to use the `etag` [response header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag). The servers provide it and we can use it as a mechanism to always download the latest files.

**Comment by tmuntaner** [comment]
@ikapelyukhin @jesusbv Have you seen this issue in your RMT instances before?

**Comment by tmuntaner** [comment]
@digitaltom This was the issue that we saw in the demo last Friday.

**Comment by lcaparroz** [comment]
Some thoughts on possible solutions for not relying on reading the file timestamp from disk:

1. Always download all metadata files, regardless of timestamp;
2. Starting keeping track of all metadata files, recording the timestamp on database and relying on it instead of the disk file;
3. Starting using both [`ETag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) and [`If-None-Match`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match) headers instead of/together with [`If-Modified-Since`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since). This solution would also require saving information on database for metadata files. The `If-None-Match` header has precedence over `If-Modified-Since`.

Reading a file's timestamp directly from disk seems to be vulnerable, prone to errors, since RMT has no control over the disk files. I guess @digitaltom mentioned some customers had issues when copying files manually, which would probably cause the timestamps to change.

**Comment by tmuntaner** [comment]
I've been thinking about this for the last few days and  here are my thoughts:

Option 1 would be the easiest, but I think that we only need to force the download of any calls of `@downloader.download()`. My only issue with this is the unnecessary download time and bandwidth.

Since the `@downloader.download` is scoped to only a few files and all of their names are static (the same across multiple mirrors), I think we can make use of these assumptions and create a database table for the cache. However, in this case, I would probably rename the method from `download` to `cached_download` to avoid its misuse in the future.

`database_table`: (`cached_metadata_files`?)
* `url` - remote location of the file
* `etag` - cache tag for the file
* `last_mirrored_at` - the time when the file was last mirrored
* `checksum_type` - checksum type for the file (optional?)
* `checksum` - checksum of the file (optional?)

**Process:**

* `@downloader.cached_download('foo')`
* (optional) use the checksum of the local file to ensure that it is still valid.
* Ask the CDN for the file using the etag.
* If you get a new file, update the cached database entry.

**Comment by ikapelyukhin** [comment]
> @ikapelyukhin @jesusbv Have you seen this issue in your RMT instances before?

Had some issues with caching but because of GPG signatures (`repomd.xml.{asc,key}`), not `repomd.xml`. QA people had some issues, but that was caused by messed up timestamps on the filesystem.

Switch from issuing a `GET` request with `Last-Modified-Since` header to issuing a `HEAD` request first, comparing the size and the timestamp and proceeding with the `GET` request without any additional headers if they don't match.

Then you don't have to store bunch of metadata in the DB and figure out how to keep the DB up-to-date and clean.
