### ISSUE TITLE
nginx default config claims entire nginx instance

### ISSUE THREAD

**Issue by olafhering** [SUSE/rmt#631]
It seems there is no easy way to hook into nginx once `rmt-server-config.rpm` is installed.

With apache and SMT is was as easy as this:
````apache
Alias /urlpart "/path/to/my/urlpart"
<Directory /path/to/my/urlpart>
  <IfModule !mod_access_compat.c>
    Require all granted
  </IfModule>
  <IfModule mod_access_compat.c>
    Order allow,deny
    Allow from all
  </IfModule>
  Options       +Indexes +Multiviews +FollowSymLinks
  IndexOptions  FancyIndexing   ScanHTMLTitles  NameWidth=*     DescriptionWidth=*
</Directory>
````

With nginx such things are not possible, especially with `listen 80   default` in `/etc/nginx/vhosts.d/rmt-server-http.conf`.

It is possible to do something like `ln -s /path/to/my/urlpart /usr/share/rmt/public/urlpart`. But this will only work reliable when `http://host/urlpart/` is used as URL. With `http://host/urlpart` an `index.html` is loaded, but every image referenced in this website is loaded as `http://host/filename` instead of `http://host/urlpart/filename`.

In addition it is not possible to browse `/urlpart` in case no `index.html` exists.

I'm not familiar with `nginx`, or `apache`. It seems the only way to really hook into `rmt-server-config`, the provided nginx config files need an `include rmt-hooks-http.d/*.conf`.

**Comment by tmuntaner** [comment]
@olafhering,

thanks for your contribution. I will bring this issue and PR #634 up with the team so we can decide how we want to continue.

Thanks,
Thomas Muntaner

**Comment by tmuntaner** [comment]
@olafhering could you please give me your intended use case?

RMT is intended to be the only web application on the server. Is there a workflow which we're missing?

**Comment by olafhering** [comment]
Why would it be a good idea to allow just a single (http) service on a machine?

A "server" just serves data, and mirrored SUSE repos are just one part of the data. It is certainly up to the admin to deal conflicts in the URLs.

In my case I export `/data` and therefore expect `http://host/data` to be browsable, and I have [chrony-graph](https://build.opensuse.org/package/show/network:time/chrony-graph) installed and expect both `http://host/chrony-graph` and `http://host/chrony-graph/` to work.

**Comment by tmuntaner** [comment]
@olafhering I've looked at the nginx files, and RMT just sets itself up as the default site for port 80 https://github.com/SUSE/rmt/blob/master/package/files/nginx/nginx-http.conf#L2.

If you create another vhost in `/etc/nginx/vhosts.d` and set the `server_name` to a new URL, then more than one website is allowed.

**Comment by olafhering** [comment]
Yes, that is the bug I think.

Why does the rmt-config claim the entire host via `default`? Would just just work if that setting is not specified? And will RMT break if another config snippet claims the host via `default`?

**Comment by tmuntaner** [comment]
RMT currently needs the `default` setting, because, otherwise, nginx would need to know exactly which URLs match RMT's and maintain that configuration file over future updates.

The `default` in nginx just shows RMT as the fallback, but it doesn't claim the entire server. If a user wants to add a new URL to nginx, he/she can add a more specific vhost. In that case, it will only fallback to RMT if the `server_name` of the vhost is not met. I tested this on my local RMT and it worked.

**Comment by olafhering** [comment]
I assume with 'add another vhost' means it is expected the admin is in control of DNS for this network actually be able to access `host` via another name?

While is may work for my `export /data via http` case, it seems to be impossible to create a generic drop-in like `chrony-graph` because it would need to know the DNS names in advance.

**Comment by tmuntaner** [comment]
@olafhering Could you clarify one thing for me: are these drop-ins related to RMT or do you intend for them to be separate websites using the same domain name?

And yes, we've expected that RMT's nginx files are used for RMT alone. The idea is that if a user wants to have a separate service, she/he could create a nginx configuration file for that specific service.

Here is the test file I created for this question:

```
server {
    listen 80;
    server_name morumotto2.suse.de;
    root   /srv/www/htdocs/;

    location / {
            root   /srv/www/htdocs/;
            index  index.html index.htm;
        }
	
    error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /srv/www/htdocs/;
        }
}
```

Where `morumotto.suse.de` and `morumotto2.suse.de` pointed at the same host. `morumotto.suse.de` defaulted to RMT while `morumotto2.suse.de` used the new configuration.

> it seems to be impossible to create a generic drop-in like `chrony-graph` because it would need to know the DNS names in advance.

Could you please explain why? Do the DNS names change?

**Comment by tmuntaner** [comment]
@olafhering I'm just following up. Do you still need help with this?

**Comment by olafhering** [comment]
Well, I have to think about it.

While I may be able to do the tedious extra work and create a vhost for each potential DNS name and for each potential numeric IP address just to serve `/data` below `http://host/data`, plugins like `chrony-graph` may requie extra work.

**Comment by olafhering** [comment]
so be it...
