### ISSUE TITLE
Limit output to desired architecture

### ISSUE THREAD

**Issue by blauerdaemon** [SUSE/rmt#655]
Let's assume I am interested in x86_64 only based repos, rmt-cli could provide an option to limit the output to only these repos. Something like:

rmt-cli products list <optional arch>
rmt-cli products list x86_64

or

rmt-cli repos list <optional arch>
rmt-cli repos list x86_64 --all

**Comment by thutterer** [comment]
So similar to #656 but for the architecture :thinking: Would make sense to have both filters `--arch foo` and `--version "bar"`, I guess.
What do you think @tmuntaner and @lcaparroz?

**Comment by jesusbv** [comment]
@thutterer I plan to include those queries in #656 
Basically, any combination of `name/version/arch`
so the `list` is a better experience
