### ISSUE TITLE
Enhance filter options for products listing

### ISSUE THREAD

**Issue by blauerdaemon** [SUSE/rmt#656]
A product version based view would be nice, like

rmt-cli products list <version>
rmt-cli products list 15 SP2 x86_64

The output should be limited to repos available for a given (service pack) version. Something like:

statler:~/ # rmt-cli products list --all | grep "15 SP2" | grep x86_64
| 1946 | Basesystem Module                                                       | 15 SP2  | x86_64  | Mirror       | 2020-11-10 13:03:38 UTC |
| 1963 | Containers Module                                                       | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1967 | Desktop Applications Module                                             | 15 SP2  | x86_64  | Mirror       | 2020-11-10 13:04:04 UTC |
| 1971 | Development Tools Module                                                | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1978 | HPC Module                                                              | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1982 | Legacy Module                                                           | 15 SP2  | x86_64  | Mirror       | 2020-11-10 13:04:16 UTC |
| 1988 | Public Cloud Module                                                     | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1992 | Python 2 Module                                                         | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1994 | SAP Applications Module                                                 | 15 SP2  | x86_64  | Mirror       | 2020-11-10 13:04:25 UTC |
| 1955 | Server Applications Module                                              | 15 SP2  | x86_64  | Mirror       | 2020-11-10 13:03:44 UTC |
| 2075 | SUSE Cloud Application Platform Tools Module                            | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1935 | SUSE Linux Enterprise Desktop                                           | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1959 | SUSE Linux Enterprise High Availability Extension                       | 15 SP2  | x86_64  | Mirror       | 2020-11-10 13:03:49 UTC |
| 1934 | SUSE Linux Enterprise High Performance Computing                        | 15 SP2  | x86_64  | Don't Mirror |                         |
| 2129 | SUSE Linux Enterprise High Performance Computing ESPOS                  | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1984 | SUSE Linux Enterprise Live Patching                                     | 15 SP2  | x86_64  | Don't Mirror |                         |
| 2003 | SUSE Linux Enterprise Real Time                                         | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1939 | SUSE Linux Enterprise Server                                            | 15 SP2  | x86_64  | Mirror       | 2020-11-10 13:04:11 UTC |
| 1941 | SUSE Linux Enterprise Server for SAP Applications                       | 15 SP2  | x86_64  | Mirror       | 2020-11-10 13:04:20 UTC |
| 1999 | SUSE Linux Enterprise Workstation Extension                             | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1950 | SUSE Package Hub                                                        | 15 SP2  | x86_64  | Don't Mirror |                         |
| 2005 | SUSE Real Time Module                                                   | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1998 | Transactional Server Module                                             | 15 SP2  | x86_64  | Don't Mirror |                         |
| 1976 | Web and Scripting Module                                                | 15 SP2  | x86_64  | Don't Mirror |                         |

but only in nice ;)
This way it would be much easier to find which repos to mirror for a given service pack.

**Comment by thutterer** [comment]
Probably nice to have, yes, but would it be really that much nicer than this? :nerd_face: 

```bash
rmt-cli products list --all | grep -A 1 "12 SP5"
```

@jesusbv Do you want to work on this?

**Comment by jesusbv** [comment]
@thutterer yes, I have an idea in mind about the behavior and output (as I faced the same problem), 
so I took the issue if that's ok

**Comment by thutterer** [comment]
This got implemented in #663
