### ISSUE TITLE
delete retracted files

### ISSUE THREAD

**Issue by ravarga** [SUSE/rmt#662]
Recently there was a retracted file in SES6 Updates repo. RMT still keeps the file in local repos. 

SMT had an option -c to clean whatever doesn't exist in SCC. Can we implement this functionality and remove such retracted files?

**Comment by thutterer** [comment]
Hi Rado, thanks for opening this issue. We just recently discussed this topic with the team and have this on our backlog now. It might take us a while until we get to it though, so I'm marking this as _help wanted_.

If you, or anyone else, would be willing to work on it, please ping us here in the issue so we can plan the implementation details.

**Comment by olafhering** [comment]
[rmt-list-orphaned-rpms.py.txt](https://github.com/SUSE/rmt/files/6213857/rmt-list-orphaned-rpms.py.txt)

A quick, simple tool to remove stale files manually. Maybe there is a `contrib/` directory for this [hw](https://hackweek.suse.com/20/projects/remove-stale-rpm-files-from-rmt-mirror) project.
