### ISSUE TITLE
nginx not listed as required package

### ISSUE THREAD

**Issue by abonillabeeche** [SUSE/rmt#671]
nginx is not mentioned as a required package under the installation steps. 

Should be:

zypper in rmt-server yast2-rmt nginx mysql

**Comment by thutterer** [comment]
Hello Alejandro! Are you referring to https://github.com/SUSE/rmt/blob/master/docs/installation.md?

I just double-checked the specfile, and rmt-server does recommend nginx and mariadb (not mysql) so just running `zypper in rmt-server` is enough to install it with all its dependencies.

Have you had a different experience?

**Comment by abonillabeeche** [comment]
Yes. I don't think the dependency was set. Can you double check? I used openSUSE and the package in OBS.

**Comment by thutterer** [comment]
SLES and openSUSE share the same [specfile](https://build.opensuse.org/package/view_file/systemsmanagement:SCC:RMT/rmt-server/rmt-server.spec?expand=1) so there shouldn't be difference in behavior.

Maybe you had zypper configured to install `--no-recommends` when you ran into the issue?

The reason these packages are not hard `Required` in the specfile is this:

https://github.com/SUSE/rmt/blob/db4e77ddac635da9c1d35b0464afbf81550fb257/package/obs/rmt-server.changes#L195-L196

@abonillabeeche Can I close this issue?

**Comment by felixsch** [comment]
It looks like there is no movement anymore. I will close this for now. In case further discussion is needed, please re-open this issue. Thanks!
