### ISSUE TITLE
Migrate from travis-ci.org to Github Actions

### ISSUE THREAD

**Issue by digitaltom** [SUSE/rmt#707]
With the [new policy](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) of travis-ci, it will be beneficial to 
move RMT testing to [Github Actions](https://github.com/features/actions).

There is documentation for how to migrate: 
https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by felixsch** [comment]
I think this is done right? I will close for now! If you think there is something missing, open again ;)
