### ISSUE TITLE
Cache files grow indefinitely, despite 20 min expiration in code.

### ISSUE THREAD

**Issue by bear454** [SUSE/rmt#738]
In Production, Rails is defaulting to file-based caching; with file caching the cache files never 'expire'... they must be removed (this is documented behavior [1]).

Eventually, `/var/lib/rmt/tmp/cache` will outgrow any disk.

**Comment by ngetahun** [comment]
@bear454 Can you shed some light on how you use rmt? Our reference hosts are functioning well, we would like to get a better understanding before we merge it to the codebase.

**Comment by bear454** [comment]
This was filed on behalf of the SUSE Public Cloud Sysadmin team; some of the RMT servers in production supporting customers in AWS/Azure/GCP have over 6GB of Rails cache entries.

**Comment by bear454** [comment]
IMO regardless of the overall volume; there's a clear problem when using ActiveSupport::Cache::Filestore as the cache files never expire.
