### ISSUE TITLE
enforce ruby 2.4.1 syntax

### ISSUE THREAD

**Issue by digitaltom** [SUSE/rmt#79]
I am receiving: 

```
> sudo ./bin/rmt-cli mirror
./bin/rmt-cli:19: syntax error, unexpected '.'
  group = Settings&.[](:cli)&.[](:group) || RMT::DEFAULT_GROUP
                    ^
./bin/rmt-cli:20: syntax error, unexpected '.'
  user = Settings&.[](:cli)&.[](:user) || RMT::DEFAULT_USER
                   ^
``` 

because .ruby-version has 2.4.1 so we can run on SLES12. 
I did not find a way to enforce a ruby version syntax in rubocop.

**Comment by ikapelyukhin** [comment]
@digitaltom, do you mean Ruby version 2.2? Because that's what is shipped in SLES12, and safe navigation operator has been added in version 2.3.

**Comment by digitaltom** [comment]
doesn't work for me on 2.4.1, maybe because of the array syntax?

**Comment by ikapelyukhin** [comment]
@digitaltom, `ruby -e 'foo = [555]; puts foo&.[](0)'` -- works on 2.4.1.
Please post the error message you are getting.

**Comment by digitaltom** [comment]
Right, my root user was using ruby 2.1...

**Comment by ikapelyukhin** [comment]
We still can look into using Ruby 2.2 syntax, so that RMT can work on SLES12 without having to install Ruby 2.4.

**Comment by digitaltom** [comment]
if that's the only place to change that would be useful. But are you sure of 2.2? I can only see 2.1 on SLES12.

**Comment by ikapelyukhin** [comment]
Not entirely sure, but I think `2.2` might be in some of the modules, while `2.4` I think is only available from OBS in some devel project.
