### ISSUE TITLE
Missing validation of the CLI input

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/rmt#81]
```
$ rmt-cli repo disable 1
/.../rmt/lib/rmt/cli/repos.rb:51:in `change_repository_mirroring': undefined method `change_mirroring!' for nil:NilClass (NoMethodError)
```

It would make sense to check all of the commands and make sure invalid input is correctly handled everywhere.

**Comment by thutterer** [comment]
For your example, there is already #55 but I agree that we should check all commands in all wrong ways to make sure we don't throw stacktraces anywhere.

**Comment by tmuntaner** [comment]
@ikapelyukhin Can you verify that you still have an issue here?

```
$ bin/rmt-cli repo disable 1                                                                                                                                                                         
Repository not found by id "1".
```

**Comment by ikapelyukhin** [comment]
@tmuntaner Yep, looks like it got fixed alongside with enabling/disabling multiple products/repos :+1:
