### ISSUE TITLE
Custom Non-SCC Mirroring with 'rmt-cli mirror'

### ISSUE THREAD

**Issue by kevinrsalisbury** [SUSE/rmt#82]
Please forgive me if this is obvious, but I need to clarify something;

Adding a non-SCC repo mirror: For example, if we add the non-SCC rmt repo for OpenSuse Leap 42.3, we run: rmt-cli mirror custom https://download.opensuse.org/repositories/systemsmanagement:/SCC:/RMT/openSUSE_Leap_42.3/ opensuse/rmt - this is only a one time event, correct? Subsequent runs of just 'rmt-cli mirror' will only mirror SCC product repos, non-SCC custom repos are not mirrored automatically at this time. Is this correct? If not correct what am I missing. If it is correct, is there any reason custom repos can't be added to the list of maintained repos for scheduled rmt-cli mirror runs by default (or perhaps enable future mirroring of the custom repo via a command in rmt-mirror)?

**Comment by ikapelyukhin** [comment]
Hello, Kevin.

We are working on implementing a proper solution for managing custom repositories (see #76). However, the feature isn't complete yet and I think this code hasn't been packaged into an RPM.

`rmt-cli mirror custom` was implemented as a placeholder to demonstrate that mirroring of non-SCC repos is possible and it indeed doesn't save the repo for future runs of `mirror` command. It is going to be removed once proper solution is implemented.

Thanks, Ivan.

**Comment by kevinrsalisbury** [comment]
Excellent, thanks Ivan.
