### ISSUE TITLE
Raise CLI errors consistently

### ISSUE THREAD

**Issue by ikapelyukhin** [SUSE/rmt#87]
We've got several CLI commands left that do something along the lines:

```ruby
if (something_wrong)
  warn "Error!"
  return
end
```

That isn't ideal, because that doesn't set the exit code. It would be better to raise `RMT::CLI::Error` instead, which is handled in `RMT::CLI::Base` to set the exit code and hide the stack trace.

**Comment by tmuntaner** [comment]
@ikapelyukhin Do you have any examples of code that shows this behavior?

I would either like to fix this, or if we already solved it, close this issue.

**Comment by ikapelyukhin** [comment]
@tmuntaner I think it was already fix in #225/#226. There seems to be only one `exit` call in `RMT::CLI` classes, closing.

**Comment by tmuntaner** [comment]
@ikapelyukhin Thanks for the update
