### ISSUE TITLE
feature: Assign regcodes for systems via rmt-cli on RMT server

### ISSUE THREAD

**Issue by jonsger** [SUSE/rmt#893]
It would be nice if one could assign regcodes via the rmt-cli interface.

So something like this
```
rmt-cli systems register --hostname=bob01 --scc-id=SCC_BEEF --regcode=ABC123
```
This would save you a login per system if you need to change a code or assign a new one...

**Comment by ngetahun** [comment]
@jonsger RMT is not allowed to assign regcodes. That task falls under SCC realm.

**Comment by jonsger** [comment]
But RMT is allowed to pass the regcodes from SUSEConnect through isn't it?

**Comment by ngetahun** [comment]
Yes, but those regcodes are synced from customer subscriptions.
