### ISSUE TITLE
"enable" and "disable" commands should output the "what"

### ISSUE THREAD

**Issue by thutterer** [SUSE/rmt#94]
Currently when you, let's say, enable a product, RMT outputs something like
`3 repositories enabled` but it does not tell you which ones. So if you by accident enter a wrong product id, you might think your action was successful, even though you just enabled wrong repos.

Plus, when you enable the same product another time, RMT tells you `0 repositories enabled`, just because they were already enabled.

Instead, it should report what exactly the situation is after your action, in a reproducable manner. Something like:
```
enabled repositories:
- foo
- bar
- baz
```

**Comment by tmuntaner** [comment]
@thutterer if this still an issue for you?

**Comment by thutterer** [comment]
It's much better now.
