### ISSUE TITLE
Update translation license headers

### ISSUE THREAD

**Issue by tacerus** [SUSE/rmt#997]
Hi,

the files under locale/ contain a boilerplate license header:

```
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the rmt package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
```

I think the files should be updated to reflect the correct license and copyright holder.

**Comment by digitaltom** [comment]
I'd suggest to just drop the last line, and fix the first one. 
Most .po files already have a first line like: 
`# English translations for rmt package.` 

Referencing to the package's license looks good to me. 
Do you want to contribute such change?

**Comment by tacerus** [comment]
Sounds easy enough. :-)
